In [ ]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

!pip install torch torchvision scikit-learn pillow

False

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
import torch
import torch.nn as nn

from torchvision import datasets, models, transforms
from torch.utils.data import DataLoader
from sklearn.metrics import roc_auc_score

In [ ]:
weights = models.ResNet50_Weights.DEFAULT
model = models.resnet50(weights=weights)

Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 171MB/s]

In [ ]:
number_of_inputs = model.fc.in_features
model.fc = nn.Linear(number_of_inputs, 2)

In [ ]:
import torchvision.models as models
resnet18 = models.resnet18(pretrained=True)
alexnet = models.alexnet(pretrained=True)
squeezenet = models.squeezenet1_0(pretrained=True)
vgg16 = models.vgg16(pretrained=True)
densenet = models.densenet161(pretrained=True)
inception = models.inception_v3(pretrained=True)
googlenet = models.googlenet(pretrained=True)
shufflenet = models.shufflenet_v2_x1_0(pretrained=True)
mobilenet_v2 = models.mobilenet_v2(pretrained=True)
mobilenet_v3_large = models.mobilenet_v3_large(pretrained=True)
mobilenet_v3_small = models.mobilenet_v3_small(pretrained=True)
resnext50_32x4d = models.resnext50_32x4d(pretrained=True)
wide_resnet50_2 = models.wide_resnet50_2(pretrained=True)
mnasnet = models.mnasnet1_0(pretrained=True)

In [ ]:
!git clone https://github.com/koowenqi/TechJam-Ctrl-Alt-Elite.git
%cd /content/TechJam-Ctrl-Alt-Elite
!ls -lah

Cloning into 'TechJam-Ctrl-Alt-Elite'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 12 (delta 1), reused 9 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), done.
Resolving deltas: 100% (1/1), done.
/content/TechJam-Ctrl-Alt-Elite
total 105M
drwxr-xr-x 3 root root 4.0K Aug 29 15:07 .
drwxr-xr-x 1 root root 4.0K Aug 29 15:07 ..
-rw-r--r-- 1 root root 105M Aug 29 15:07 archive.zip
drwxr-xr-x 9 root root 4.0K Aug 29 15:07 .git
-rw-r--r-- 1 root root   42 Aug 29 15:07 .gitattributes
-rw-r--r-- 1 root root    0 Aug 29 15:07 home
-rw-r--r-- 1 root root   24 Aug 29 15:07 README.md

In [ ]:
from pathlib import Path
import zipfile

archive_path = Path("archive.zip")

print("Archive exists:", archive_path.exists())

if archive_path.exists():
    print(
        "Archive size:",
        round(archive_path.stat().st_size / (1024 ** 2), 2),
        "MB"
    )

    print("Valid ZIP:", zipfile.is_zipfile(archive_path))

Archive exists: True
Archive size: 104.55 MB
Valid ZIP: True

In [ ]:
!git lfs install
!git lfs pull

Updated Git hooks.
Git LFS initialized.

In [ ]:
with zipfile.ZipFile(archive_path, "r") as archive:
    names = archive.namelist()

print("Files inside archive:", len(names))
print("\nFirst 30 paths:")

for name in names[:30]:
    print(name)

Files inside archive: 120000

First 30 paths:
test/FAKE/0 (10).jpg
test/FAKE/0 (2).jpg
test/FAKE/0 (3).jpg
test/FAKE/0 (4).jpg
test/FAKE/0 (5).jpg
test/FAKE/0 (6).jpg
test/FAKE/0 (7).jpg
test/FAKE/0 (8).jpg
test/FAKE/0 (9).jpg
test/FAKE/0.jpg
test/FAKE/1 (10).jpg
test/FAKE/1 (2).jpg
test/FAKE/1 (3).jpg
test/FAKE/1 (4).jpg
test/FAKE/1 (5).jpg
test/FAKE/1 (6).jpg
test/FAKE/1 (7).jpg
test/FAKE/1 (8).jpg
test/FAKE/1 (9).jpg
test/FAKE/1.jpg
test/FAKE/10 (10).jpg
test/FAKE/10 (2).jpg
test/FAKE/10 (3).jpg
test/FAKE/10 (4).jpg
test/FAKE/10 (5).jpg
test/FAKE/10 (6).jpg
test/FAKE/10 (7).jpg
test/FAKE/10 (8).jpg
test/FAKE/10 (9).jpg
test/FAKE/10.jpg

In [ ]:
from pathlib import Path
import zipfile

output_directory = Path("training")
output_directory.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile("archive.zip", "r") as archive:
    archive.extractall(output_directory)

print("Extraction completed:", output_directory.resolve())

Extraction completed: /content/TechJam-Ctrl-Alt-Elite/training

In [ ]:
from pathlib import Path

training_directory = Path("training")

for path in sorted(training_directory.rglob("*")):
    if path.is_dir():
        print(path)

training/test
training/test/FAKE
training/test/REAL
training/train
training/train/FAKE
training/train/REAL

In [ ]:
from pathlib import Path

IMAGE_EXTENSIONS = {
    ".jpg", ".jpeg", ".png",
    ".webp", ".bmp", ".tif", ".tiff"
}

def contains_images(directory):
    return any(
        file.is_file() and file.suffix.lower() in IMAGE_EXTENSIONS
        for file in directory.rglob("*")
    )

candidate_roots = []

directories_to_check = [
    training_directory,
    *[
        path
        for path in training_directory.rglob("*")
        if path.is_dir()
    ]
]

for directory in directories_to_check:
    class_directories = [
        child
        for child in directory.iterdir()
        if child.is_dir() and contains_images(child)
    ]

    if len(class_directories) >= 2:
        candidate_roots.append(
            (
                directory,
                [child.name for child in class_directories]
            )
        )

print("Possible dataset roots:")

for index, candidate in enumerate(candidate_roots):
    print(index, candidate)

Possible dataset roots:
0 (PosixPath('training'), ['test', 'train'])
1 (PosixPath('training/test'), ['REAL', 'FAKE'])
2 (PosixPath('training/train'), ['REAL', 'FAKE'])

In [ ]:
TRAIN_ROOT = next(
    path
    for path, classes in candidate_roots
    if path.name.lower() in {"train", "training"}
)

print("Selected training root:", TRAIN_ROOT)

Selected training root: training

In [ ]:
from pathlib import Path

training_directory = Path("training")

for path in sorted(training_directory.rglob("*")):
    if path.is_dir():
        direct_subfolders = [
            child.name
            for child in path.iterdir()
            if child.is_dir()
        ]

        print(path, "→", direct_subfolders)

training/test → ['REAL', 'FAKE']
training/test/FAKE → []
training/test/REAL → []
training/train → ['REAL', 'FAKE']
training/train/FAKE → []
training/train/REAL → []

In [ ]:
TRAIN_ROOT = Path("training/train")

print("Training root:", TRAIN_ROOT)
print(
    "Class folders:",
    [
        folder.name
        for folder in TRAIN_ROOT.iterdir()
        if folder.is_dir()
    ]
)

Training root: training/train
Class folders: ['REAL', 'FAKE']

In [ ]:
IMAGE_EXTENSIONS = {
    ".jpg", ".jpeg", ".png",
    ".webp", ".bmp", ".tif", ".tiff"
}

for class_directory in sorted(TRAIN_ROOT.iterdir()):

    if class_directory.is_dir():

        image_count = sum(
            1
            for file in class_directory.rglob("*")
            if file.is_file()
            and file.suffix.lower() in IMAGE_EXTENSIONS
        )

        print(class_directory.name, image_count)

FAKE 50000
REAL 50000

In [ ]:
from pathlib import Path

ORIGINAL_TRAIN_ROOT = Path("training/train")
ORIGINAL_TEST_ROOT = Path("training/test")

print(ORIGINAL_TRAIN_ROOT.exists())
print(ORIGINAL_TEST_ROOT.exists())

True
True

In [ ]:
from torchvision import datasets

original_train_dataset = datasets.ImageFolder(
    ORIGINAL_TRAIN_ROOT
)

original_test_dataset = datasets.ImageFolder(
    ORIGINAL_TEST_ROOT
)

print(
    "Original training mapping:",
    original_train_dataset.class_to_idx
)

print(
    "Original test mapping:",
    original_test_dataset.class_to_idx
)

Original training mapping: {'FAKE': 0, 'REAL': 1}
Original test mapping: {'FAKE': 0, 'REAL': 1}

In [ ]:
assert (
    original_train_dataset.class_to_idx
    ==
    original_test_dataset.class_to_idx
), "Train and test class mappings do not match"

In [ ]:
all_samples = (
    original_train_dataset.samples
    +
    original_test_dataset.samples
)

all_paths = [
    path
    for path, label in all_samples
]

all_labels = [
    label
    for path, label in all_samples
]

print("Combined images:", len(all_samples))

Combined images: 120000

In [ ]:
from collections import Counter

print(
    "Combined class counts:",
    Counter(all_labels)
)

Combined class counts: Counter({0: 60000, 1: 60000})

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

SEED = 2026

all_indices = np.arange(
    len(all_samples)
)

train_indices, remaining_indices = train_test_split(
    all_indices,
    test_size=0.30,
    random_state=SEED,
    stratify=np.array(all_labels)
)

In [ ]:
remaining_labels = np.array(all_labels)[
    remaining_indices
]

validation_indices, test_indices = train_test_split(
    remaining_indices,
    test_size=0.50,
    random_state=SEED,
    stratify=remaining_labels
)

In [ ]:
print("Training:", len(train_indices))
print("Validation:", len(validation_indices))
print("Test:", len(test_indices))

Training: 84000
Validation: 18000
Test: 18000

In [ ]:
def show_split_counts(name, indices):
    split_labels = [
        all_labels[index]
        for index in indices
    ]

    print(
        name,
        len(indices),
        Counter(split_labels)
    )

show_split_counts(
    "Training",
    train_indices
)

show_split_counts(
    "Validation",
    validation_indices
)

show_split_counts(
    "Test",
    test_indices
)

Training 84000 Counter({0: 42000, 1: 42000})
Validation 18000 Counter({1: 9000, 0: 9000})
Test 18000 Counter({1: 9000, 0: 9000})

In [ ]:
from PIL import Image, ImageOps
from torch.utils.data import Dataset

class ImagePathDataset(Dataset):

    def __init__(
        self,
        samples,
        indices,
        transform
    ):
        self.samples = [
            samples[index]
            for index in indices
        ]

        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, index):

        image_path, label = self.samples[index]

        with Image.open(image_path) as image:
            image = ImageOps.exif_transpose(
                image
            ).convert("RGB")

        if self.transform is not None:
            image = self.transform(image)

        return image, label

In [ ]:
train_dataset = ImagePathDataset(
    all_samples,
    train_indices,
    train_transform
)

validation_dataset = ImagePathDataset(
    all_samples,
    validation_indices,
    validation_transform
)

test_dataset = ImagePathDataset(
    all_samples,
    test_indices,
    validation_transform
)

In [ ]:
print("Training dataset:", len(train_dataset))
print("Validation dataset:", len(validation_dataset))
print("Test dataset:", len(test_dataset))

Training dataset: 84000
Validation dataset: 18000
Test dataset: 18000

In [ ]:
from torch.utils.data import DataLoader

BATCH_SIZE = 64

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

In [ ]:
class_to_idx = (
    original_train_dataset.class_to_idx
)

print(class_to_idx)

{'FAKE': 0, 'REAL': 1}

In [ ]:
AI_CLASS_INDEX = class_to_idx["FAKE"]
REAL_CLASS_INDEX = class_to_idx["REAL"]

print("AI class:", AI_CLASS_INDEX)
print("Real class:", REAL_CLASS_INDEX)

AI class: 0
Real class: 1

In [ ]:
print(original_train_dataset.class_to_idx)

{'FAKE': 0, 'REAL': 1}

In [ ]:
AI_CLASS_INDEX = original_train_dataset.class_to_idx["FAKE"]

print("AI class index:", AI_CLASS_INDEX)

AI class index: 0

In [ ]:
print(model.fc)

Linear(in_features=2048, out_features=2, bias=True)

In [ ]:
images, labels = next(
    iter(validation_loader)
)

print("Images shape:", images.shape)
print("Labels shape:", labels.shape)
print("First labels:", labels[:10])

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fd962312520>Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fd962312520>

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1709, in __del__
        self._shutdown_workers()self._shutdown_workers()

  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py", line 1692, in _shutdown_workers
    if w.is_alive():
if w.is_alive():  File "/usr/lib/python3.13/multiprocessing/process.py", line 160, in is_alive

assert self._parent_pid == os.getpid(), 'can only test a child process'  File "/usr/lib/python3.13/multiprocessing/process.py", line 160, in is_alive

    AssertionErrorassert self._parent_pid == os.getpid(), 'can only test a child process':
can only test a child processAssertionError
: can only test a child process

Images shape: torch.Size([64, 3, 224, 224])
Labels shape: torch.Size([64])
First labels: tensor([1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [ ]:
del train_loader
del validation_loader
del test_loader

In [ ]:
from torch.utils.data import DataLoader
import torch

BATCH_SIZE = 64

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

validation_loader = DataLoader(
    validation_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

In [ ]:
images, labels = next(
    iter(validation_loader)
)

print("Images shape:", images.shape)
print("Labels shape:", labels.shape)
print("First labels:", labels[:10])

Images shape: torch.Size([64, 3, 224, 224])
Labels shape: torch.Size([64])
First labels: tensor([1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [ ]:
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Selected device:", device)

if device.type == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))

Selected device: cuda
GPU: Tesla T4

In [ ]:
model = model.to(device)

In [ ]:
images = images.to(device)
labels = labels.to(device)

model.eval()

with torch.no_grad():
    outputs = model(images)

print("Outputs shape:", outputs.shape)
print("First output:", outputs[0])

Outputs shape: torch.Size([64, 2])
First output: tensor([0.0313, 0.1054], device='cuda:0')

In [ ]:
probabilities = torch.softmax(
    outputs,
    dim=1
)

print(
    "First probabilities:",
    probabilities[0]
)

print(
    "Sum:",
    probabilities[0].sum()
)

First probabilities: tensor([0.4815, 0.5185], device='cuda:0')
Sum: tensor(1., device='cuda:0')

In [ ]:
images = images.to(device)
labels = labels.to(device)

model.eval()

with torch.no_grad():
    outputs = model(images)

print("Outputs shape:", outputs.shape)
print("First output:", outputs[0])

Outputs shape: torch.Size([64, 2])
First output: tensor([0.0313, 0.1054], device='cuda:0')

In [ ]:
print("Device:", device)
print("Model output layer:", model.fc)
print("Training batches:", len(train_loader))
print("Validation batches:", len(validation_loader))
print("Class mapping:", original_train_dataset.class_to_idx)

Device: cuda
Model output layer: Linear(in_features=2048, out_features=2, bias=True)
Training batches: 1313
Validation batches: 282
Class mapping: {'FAKE': 0, 'REAL': 1}

In [ ]:
AI_CLASS_INDEX = original_train_dataset.class_to_idx["FAKE"]
REAL_CLASS_INDEX = original_train_dataset.class_to_idx["REAL"]

print("AI class index:", AI_CLASS_INDEX)
print("Real class index:", REAL_CLASS_INDEX)

AI class index: 0
Real class index: 1

In [ ]:
import torch
import torch.nn as nn

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=0.0001,
    weight_decay=0.0001
)

use_mixed_precision = device.type == "cuda"

scaler = torch.amp.GradScaler(
    "cuda",
    enabled=use_mixed_precision
)

In [ ]:
from tqdm.auto import tqdm

model.train()

running_loss = 0.0
correct_predictions = 0
images_processed = 0

progress_bar = tqdm(
    train_loader,
    desc="Training epoch 1"
)

for images, labels in progress_bar:

    images = images.to(
        device,
        non_blocking=True
    )

    labels = labels.to(
        device,
        non_blocking=True
    )

    optimizer.zero_grad(
        set_to_none=True
    )

    with torch.autocast(
        device_type=device.type,
        dtype=torch.float16,
        enabled=use_mixed_precision
    ):
        outputs = model(images)
        loss = criterion(outputs, labels)

    scaler.scale(loss).backward()
    scaler.step(optimizer)
    scaler.update()

    batch_size = images.size(0)

    running_loss += (
        loss.item() * batch_size
    )

    predictions = outputs.argmax(
        dim=1
    )

    correct_predictions += (
        predictions == labels
    ).sum().item()

    images_processed += batch_size

    current_loss = (
        running_loss / images_processed
    )

    current_accuracy = (
        correct_predictions
        / images_processed
    )

    progress_bar.set_postfix(
        loss=f"{current_loss:.4f}",
        accuracy=f"{current_accuracy:.4f}"
    )

training_loss = (
    running_loss / images_processed
)

training_accuracy = (
    correct_predictions / images_processed
)

print("Epoch 1 completed")
print("Training loss:", training_loss)
print("Training accuracy:", training_accuracy)

Training epoch 1:   0%|          | 0/1313 [00:00<?, ?it/s]

Epoch 1 completed
Training loss: 0.1632956434034166
Training accuracy: 0.9352976190476191

In [ ]:
from sklearn.metrics import roc_auc_score
from tqdm.auto import tqdm

model.eval()

validation_labels = []
validation_scores = []

validation_correct = 0
validation_total = 0

with torch.no_grad():

    for images, labels in tqdm(
        validation_loader,
        desc="Validating"
    ):

        images = images.to(
            device,
            non_blocking=True
        )

        labels = labels.to(
            device,
            non_blocking=True
        )

        with torch.autocast(
            device_type=device.type,
            dtype=torch.float16,
            enabled=use_mixed_precision
        ):
            outputs = model(images)

        probabilities = torch.softmax(
            outputs,
            dim=1
        )

        ai_probabilities = probabilities[
            :,
            AI_CLASS_INDEX
        ]

        predictions = outputs.argmax(
            dim=1
        )

        validation_correct += (
            predictions == labels
        ).sum().item()

        validation_total += (
            labels.size(0)
        )

        binary_ai_labels = (
            labels == AI_CLASS_INDEX
        ).int()

        validation_labels.extend(
            binary_ai_labels
            .cpu()
            .numpy()
            .tolist()
        )

        validation_scores.extend(
            ai_probabilities
            .cpu()
            .numpy()
            .tolist()
        )

validation_accuracy = (
    validation_correct
    / validation_total
)

validation_auc = roc_auc_score(
    validation_labels,
    validation_scores
)

print("Validation images:", validation_total)
print("Validation accuracy:", validation_accuracy)
print("Validation ROC AUC:", validation_auc)

Validating:   0%|          | 0/282 [00:00<?, ?it/s]

Validation images: 18000
Validation accuracy: 0.965
Validation ROC AUC: 0.9954998950617284

In [ ]:
checkpoint = {
    "model_name": "resnet50",
    "epoch": 1,
    "model_state": model.state_dict(),
    "class_to_idx": original_train_dataset.class_to_idx,
    "ai_class_index": AI_CLASS_INDEX,
    "training_loss": training_loss,
    "training_accuracy": training_accuracy,
    "validation_accuracy": validation_accuracy,
    "validation_auc": validation_auc,
    "image_size": 224,
    "learning_rate": 0.0001,
    "random_seed": 2026
}

torch.save(
    checkpoint,
    "/content/resnet50_epoch1.pth"
)

print("Checkpoint saved")

Checkpoint saved

In [ ]:
import numpy as np

np.savez(
    "/content/data_split_70_15_15.npz",
    train_indices=train_indices,
    validation_indices=validation_indices,
    test_indices=test_indices
)

print("Split indices saved")

Split indices saved

In [ ]:
from google.colab import files

files.download(
    "/content/resnet50_epoch1.pth"
)

In [ ]:
files.download(
    "/content/data_split_70_15_15.npz"
)

In [ ]:
from torch.utils.data import DataLoader
from sklearn.metrics import roc_auc_score
from tqdm.auto import tqdm
import torch

def evaluate_dataset(
    dataset,
    description,
    batch_size=64
):
    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

    model.eval()

    all_labels = []
    all_ai_scores = []

    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in tqdm(
            loader,
            desc=description
        ):

            images = images.to(
                device,
                non_blocking=True
            )

            labels = labels.to(
                device,
                non_blocking=True
            )

            with torch.autocast(
                device_type=device.type,
                dtype=torch.float16,
                enabled=use_mixed_precision
            ):
                outputs = model(images)

            probabilities = torch.softmax(
                outputs,
                dim=1
            )

            ai_probabilities = probabilities[
                :,
                AI_CLASS_INDEX
            ]

            predictions = outputs.argmax(
                dim=1
            )

            correct += (
                predictions == labels
            ).sum().item()

            total += labels.size(0)

            binary_ai_labels = (
                labels == AI_CLASS_INDEX
            ).int()

            all_labels.extend(
                binary_ai_labels
                .cpu()
                .numpy()
                .tolist()
            )

            all_ai_scores.extend(
                ai_probabilities
                .cpu()
                .numpy()
                .tolist()
            )

    accuracy = correct / total

    auc = roc_auc_score(
        all_labels,
        all_ai_scores
    )

    return {
        "images": total,
        "accuracy": accuracy,
        "auc": auc
    }

In [ ]:
clean_test_result = evaluate_dataset(
    test_dataset,
    "Evaluating clean test set"
)

print(clean_test_result)

Evaluating clean test set:   0%|          | 0/282 [00:00<?, ?it/s]

{'images': 18000, 'accuracy': 0.9654444444444444, 'auc': np.float64(0.9951757345679013)}

In [ ]:
import io
import numpy as np

from PIL import (
    Image,
    ImageEnhance,
    ImageFilter
)

from torchvision import transforms

In [ ]:
class JPEGCompression:

    def __init__(self, quality):
        self.quality = quality

    def __call__(self, image):

        buffer = io.BytesIO()

        image.save(
            buffer,
            format="JPEG",
            quality=self.quality
        )

        buffer.seek(0)

        with Image.open(buffer) as compressed:
            return compressed.convert("RGB")

In [ ]:
class DownscaleUpscale:

    def __init__(self, scale):
        self.scale = scale

    def __call__(self, image):

        original_width, original_height = (
            image.size
        )

        smaller_size = (
            max(
                1,
                round(
                    original_width
                    * self.scale
                )
            ),
            max(
                1,
                round(
                    original_height
                    * self.scale
                )
            )
        )

        smaller = image.resize(
            smaller_size,
            Image.Resampling.BICUBIC
        )

        return smaller.resize(
            (
                original_width,
                original_height
            ),
            Image.Resampling.BICUBIC
        )

In [ ]:
class DownscaleUpscale:

    def __init__(self, scale):
        self.scale = scale

    def __call__(self, image):

        original_width, original_height = (
            image.size
        )

        smaller_size = (
            max(
                1,
                round(
                    original_width
                    * self.scale
                )
            ),
            max(
                1,
                round(
                    original_height
                    * self.scale
                )
            )
        )

        smaller = image.resize(
            smaller_size,
            Image.Resampling.BICUBIC
        )

        return smaller.resize(
            (
                original_width,
                original_height
            ),
            Image.Resampling.BICUBIC
        )

In [ ]:
class CenterCropPercent:

    def __init__(self, percentage):
        self.percentage = percentage

    def __call__(self, image):

        width, height = image.size

        crop_width = round(
            width * self.percentage
        )

        crop_height = round(
            height * self.percentage
        )

        left = (
            width - crop_width
        ) // 2

        top = (
            height - crop_height
        ) // 2

        cropped = image.crop(
            (
                left,
                top,
                left + crop_width,
                top + crop_height
            )
        )

        return cropped.resize(
            (width, height),
            Image.Resampling.BICUBIC
        )

In [ ]:
class FixedColorAdjustment:

    def __init__(
        self,
        brightness,
        contrast,
        saturation
    ):
        self.brightness = brightness
        self.contrast = contrast
        self.saturation = saturation

    def __call__(self, image):

        image = ImageEnhance.Brightness(
            image
        ).enhance(
            self.brightness
        )

        image = ImageEnhance.Contrast(
            image
        ).enhance(
            self.contrast
        )

        image = ImageEnhance.Color(
            image
        ).enhance(
            self.saturation
        )

        return image

In [ ]:
class AddGaussianNoise:

    def __init__(self, sigma):
        self.sigma = sigma

    def __call__(self, tensor):

        noise = torch.randn_like(
            tensor
        ) * self.sigma

        return torch.clamp(
            tensor + noise,
            0.0,
            1.0
        )

In [ ]:
normalisation = transforms.Normalize(
    mean=[0.485, 0.456, 0.406],
    std=[0.229, 0.224, 0.225]
)

In [ ]:
jpeg30_transform = transforms.Compose([
    JPEGCompression(quality=30),
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    normalisation
])

In [ ]:
blur2_transform = transforms.Compose([
    transforms.GaussianBlur(
        kernel_size=5,
        sigma=2.0
    ),
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    normalisation
])

In [ ]:
resize025_transform = transforms.Compose([
    DownscaleUpscale(scale=0.25),
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    normalisation
])

In [ ]:
noise010_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    AddGaussianNoise(sigma=0.10),
    normalisation
])

In [ ]:
color120_transform = transforms.Compose([
    FixedColorAdjustment(
        brightness=1.2,
        contrast=1.2,
        saturation=1.2
    ),
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    normalisation
])

In [ ]:
crop080_transform = transforms.Compose([
    CenterCropPercent(
        percentage=0.8
    ),
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    normalisation
])

In [ ]:
jpeg30_test_dataset = ImagePathDataset(
    all_samples,
    test_indices,
    jpeg30_transform
)

blur2_test_dataset = ImagePathDataset(
    all_samples,
    test_indices,
    blur2_transform
)

resize025_test_dataset = ImagePathDataset(
    all_samples,
    test_indices,
    resize025_transform
)

noise010_test_dataset = ImagePathDataset(
    all_samples,
    test_indices,
    noise010_transform
)

color120_test_dataset = ImagePathDataset(
    all_samples,
    test_indices,
    color120_transform
)

crop080_test_dataset = ImagePathDataset(
    all_samples,
    test_indices,
    crop080_transform
)

In [ ]:
torch.manual_seed(SEED)

robustness_results = {
    "clean": clean_test_result,

    "jpeg_quality_30": evaluate_dataset(
        jpeg30_test_dataset,
        "JPEG quality 30"
    ),

    "blur_sigma_2": evaluate_dataset(
        blur2_test_dataset,
        "Blur sigma 2.0"
    ),

    "resize_0.25": evaluate_dataset(
        resize025_test_dataset,
        "Resize 0.25"
    ),

    "noise_sigma_0.10": evaluate_dataset(
        noise010_test_dataset,
        "Noise sigma 0.10"
    ),

    "color_plus_20": evaluate_dataset(
        color120_test_dataset,
        "Colour adjustment +20%"
    ),

    "crop_80": evaluate_dataset(
        crop080_test_dataset,
        "Centre crop 80%"
    )
}

JPEG quality 30:   0%|          | 0/282 [00:00<?, ?it/s]

Blur sigma 2.0:   0%|          | 0/282 [00:00<?, ?it/s]

Resize 0.25:   0%|          | 0/282 [00:00<?, ?it/s]

Noise sigma 0.10:   0%|          | 0/282 [00:00<?, ?it/s]

Colour adjustment +20%:   0%|          | 0/282 [00:00<?, ?it/s]

Centre crop 80%:   0%|          | 0/282 [00:00<?, ?it/s]

In [ ]:
for condition, result in robustness_results.items():

    print(
        condition,
        "accuracy:",
        round(
            result["accuracy"],
            4
        ),
        "AUC:",
        round(
            result["auc"],
            4
        )
    )

clean accuracy: 0.9654 AUC: 0.9952
jpeg_quality_30 accuracy: 0.9253 AUC: 0.9818
blur_sigma_2 accuracy: 0.5592 AUC: 0.6144
resize_0.25 accuracy: 0.5364 AUC: 0.6266
noise_sigma_0.10 accuracy: 0.5022 AUC: 0.5422
color_plus_20 accuracy: 0.9048 AUC: 0.9859
crop_80 accuracy: 0.8123 AUC: 0.9753

In [ ]:
robust_condition_aucs = [
    result["auc"]
    for condition, result
    in robustness_results.items()
    if condition != "clean"
]

initial_robust_auc = np.mean(
    robust_condition_aucs
)

initial_final_score = (
    0.5 * clean_test_result["auc"]
    +
    0.5 * initial_robust_auc
)

print(
    "Clean AUC:",
    clean_test_result["auc"]
)

print(
    "Initial robust AUC:",
    initial_robust_auc
)

print(
    "Initial combined score:",
    initial_final_score
)

Clean AUC: 0.9951757345679013
Initial robust AUC: 0.7877034537037036
Initial combined score: 0.8914395941358024

In [ ]:
import json

with open(
    "/content/robustness_results_epoch1.json",
    "w"
) as file:

    json.dump(
        robustness_results,
        file,
        indent=2
    )

print("Robustness results saved")

Robustness results saved

In [ ]:
print(original_train_dataset.class_to_idx)

AI_CLASS_INDEX = original_train_dataset.class_to_idx["FAKE"]
print("AI class index:", AI_CLASS_INDEX)

{'FAKE': 0, 'REAL': 1}
AI class index: 0

In [ ]:
test_dataset = ImagePathDataset(
    all_samples,
    test_indices,
    validation_transform
)

test_loader = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

print("Test images:", len(test_dataset))

Test images: 18000

In [ ]:
from sklearn.metrics import accuracy_score, roc_auc_score
import numpy as np
import torch

model.eval()

all_labels = []
all_ai_probabilities = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)

        outputs = model(images)
        probabilities = torch.softmax(outputs, dim=1)
        ai_probabilities = probabilities[:, AI_CLASS_INDEX]

        all_labels.extend(labels.cpu().numpy())
        all_ai_probabilities.extend(ai_probabilities.cpu().numpy())

all_labels = np.array(all_labels)
all_ai_probabilities = np.array(all_ai_probabilities)

# Convert labels into: 1 = AI, 0 = real
binary_ai_labels = (all_labels == AI_CLASS_INDEX).astype(int)

# Probability >= 0.5 means predicted AI
predicted_ai_labels = (all_ai_probabilities >= 0.5).astype(int)

test_accuracy = accuracy_score(
    binary_ai_labels,
    predicted_ai_labels
)

test_roc_auc = roc_auc_score(
    binary_ai_labels,
    all_ai_probabilities
)

print("Clean test images:", len(all_labels))
print("Clean test accuracy:", round(test_accuracy, 4))
print("Clean test ROC AUC:", round(test_roc_auc, 4))

Clean test images: 18000
Clean test accuracy: 0.9655
Clean test ROC AUC: 0.9952

In [ ]:
checkpoint = {
    "model_state_dict": model.state_dict(),
    "class_to_idx": original_train_dataset.class_to_idx,
    "ai_class_index": AI_CLASS_INDEX,
    "validation_accuracy": 0.965,
    "validation_roc_auc": 0.9954998950617284,
    "test_accuracy": test_accuracy,
    "test_roc_auc": test_roc_auc
}

torch.save(checkpoint, "/content/resnet50_epoch1.pth")

print("Saved model to /content/resnet50_epoch1.pth")

Saved model to /content/resnet50_epoch1.pth

In [ ]:
from google.colab import files
files.download("/content/resnet50_epoch1.pth")

In [ ]:
import io
import numpy as np
import torch

from PIL import Image
from torchvision import transforms
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, roc_auc_score


class JPEGCompression:
    def __init__(self, quality):
        self.quality = quality

    def __call__(self, image):
        buffer = io.BytesIO()

        image.save(
            buffer,
            format="JPEG",
            quality=self.quality
        )

        buffer.seek(0)

        compressed_image = Image.open(buffer).convert("RGB")
        compressed_image.load()

        return compressed_image


jpeg30_transform = transforms.Compose([
    JPEGCompression(quality=30),
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


jpeg30_test_dataset = ImagePathDataset(
    all_samples,
    test_indices,
    jpeg30_transform
)


jpeg30_test_loader = DataLoader(
    jpeg30_test_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)


model.eval()

jpeg30_labels = []
jpeg30_ai_probabilities = []

with torch.no_grad():
    for images, labels in jpeg30_test_loader:
        images = images.to(device)

        outputs = model(images)
        probabilities = torch.softmax(outputs, dim=1)
        ai_probabilities = probabilities[:, AI_CLASS_INDEX]

        jpeg30_labels.extend(labels.cpu().numpy())
        jpeg30_ai_probabilities.extend(
            ai_probabilities.cpu().numpy()
        )


jpeg30_labels = np.array(jpeg30_labels)
jpeg30_ai_probabilities = np.array(jpeg30_ai_probabilities)

jpeg30_binary_labels = (
    jpeg30_labels == AI_CLASS_INDEX
).astype(int)

jpeg30_predictions = (
    jpeg30_ai_probabilities >= 0.5
).astype(int)


jpeg30_accuracy = accuracy_score(
    jpeg30_binary_labels,
    jpeg30_predictions
)

jpeg30_roc_auc = roc_auc_score(
    jpeg30_binary_labels,
    jpeg30_ai_probabilities
)


print("JPEG quality 30 images:", len(jpeg30_labels))
print("JPEG quality 30 accuracy:", round(jpeg30_accuracy, 4))
print("JPEG quality 30 ROC AUC:", round(jpeg30_roc_auc, 4))

print()
print(
    "Accuracy drop:",
    round(test_accuracy - jpeg30_accuracy, 4)
)

print(
    "ROC AUC drop:",
    round(test_roc_auc - jpeg30_roc_auc, 4)
)

JPEG quality 30 images: 18000
JPEG quality 30 accuracy: 0.9249
JPEG quality 30 ROC AUC: 0.9819

Accuracy drop: 0.0406
ROC AUC drop: 0.0133

In [ ]:
def evaluate_model(dataset, name, batch_size=64):
    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

    model.eval()

    evaluation_labels = []
    evaluation_probabilities = []

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device)

            outputs = model(images)
            probabilities = torch.softmax(outputs, dim=1)
            ai_probabilities = probabilities[:, AI_CLASS_INDEX]

            evaluation_labels.extend(labels.cpu().numpy())
            evaluation_probabilities.extend(
                ai_probabilities.cpu().numpy()
            )

    evaluation_labels = np.array(evaluation_labels)
    evaluation_probabilities = np.array(evaluation_probabilities)

    binary_labels = (
        evaluation_labels == AI_CLASS_INDEX
    ).astype(int)

    predictions = (
        evaluation_probabilities >= 0.5
    ).astype(int)

    accuracy = accuracy_score(binary_labels, predictions)
    roc_auc = roc_auc_score(
        binary_labels,
        evaluation_probabilities
    )

    result = {
        "condition": name,
        "images": len(binary_labels),
        "accuracy": float(accuracy),
        "roc_auc": float(roc_auc)
    }

    print(name)
    print("Images:", result["images"])
    print("Accuracy:", round(result["accuracy"], 4))
    print("ROC AUC:", round(result["roc_auc"], 4))

    return result

In [ ]:
blur2_transform = transforms.Compose([
    transforms.GaussianBlur(
        kernel_size=5,
        sigma=2.0
    ),
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

blur2_validation_dataset = ImagePathDataset(
    all_samples,
    validation_indices,
    blur2_transform
)

blur2_result = evaluate_model(
    blur2_validation_dataset,
    "Gaussian blur sigma 2.0"
)

Gaussian blur sigma 2.0
Images: 18000
Accuracy: 0.5526
ROC AUC: 0.6085

In [ ]:
blur2_224_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),

    # Apply blur at the model's input resolution
    transforms.GaussianBlur(
        kernel_size=5,
        sigma=2.0
    ),

    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

blur2_224_validation_dataset = ImagePathDataset(
    all_samples,
    validation_indices,
    blur2_224_transform
)

blur2_224_result = evaluate_model(
    blur2_224_validation_dataset,
    "Gaussian blur sigma 2.0 at 224px"
)

Gaussian blur sigma 2.0 at 224px
Images: 18000
Accuracy: 0.9678
ROC AUC: 0.9957

In [ ]:
print("Clean validation AUC:      ", round(0.9954998950617284, 4))
print("Blurred at native 32px AUC:", round(blur2_result["roc_auc"], 4))
print("Blurred at 224px AUC:      ", round(blur2_224_result["roc_auc"], 4))
#The baseline is highly robust to Gaussian blur at its 224×224 operating resolution, but fails when severe degradation is applied directly to an already tiny 32×32 image.

Clean validation AUC:       0.9955
Blurred at native 32px AUC: 0.6085
Blurred at 224px AUC:       0.9957

In [ ]:
from torchvision.transforms import functional as TF
from torchvision.transforms import InterpolationMode


class DownscaleUpscale:
    def __init__(self, scale):
        self.scale = scale

    def __call__(self, image):
        original_width, original_height = image.size

        small_width = max(1, int(original_width * self.scale))
        small_height = max(1, int(original_height * self.scale))

        image = TF.resize(
            image,
            [small_height, small_width],
            interpolation=InterpolationMode.BILINEAR
        )

        image = TF.resize(
            image,
            [original_height, original_width],
            interpolation=InterpolationMode.BILINEAR
        )

        return image

In [ ]:
resize025_transform = transforms.Compose([
    # Establish the model's normal 224×224 input
    transforms.Resize(256),
    transforms.CenterCrop(224),

    # 224×224 → 56×56 → 224×224
    DownscaleUpscale(scale=0.25),

    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

resize025_validation_dataset = ImagePathDataset(
    all_samples,
    validation_indices,
    resize025_transform
)

resize025_result = evaluate_model(
    resize025_validation_dataset,
    "Downscale 0.25x and upscale"
)

Downscale 0.25x and upscale
Images: 18000
Accuracy: 0.8131
ROC AUC: 0.988

In [ ]:
print("Clean validation AUC:", round(0.9954998950617284, 4))
print("Resize 0.25x AUC:    ", round(resize025_result["roc_auc"], 4))
print(
    "AUC drop:            ",
    round(0.9954998950617284 - resize025_result["roc_auc"], 4)
)

Clean validation AUC: 0.9955
Resize 0.25x AUC:     0.988
AUC drop:             0.0075

In [ ]:
class AddGaussianNoise:
    def __init__(self, sigma):
        self.sigma = sigma

    def __call__(self, tensor):
        noise = torch.randn_like(tensor) * self.sigma
        noisy_tensor = tensor + noise

        return torch.clamp(
            noisy_tensor,
            min=0.0,
            max=1.0
        )

In [ ]:
noise010_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),

    # Add strong noise while pixels are still in [0, 1]
    AddGaussianNoise(sigma=0.10),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

noise010_validation_dataset = ImagePathDataset(
    all_samples,
    validation_indices,
    noise010_transform
)

In [ ]:
torch.manual_seed(2026)

noise010_result = evaluate_model(
    noise010_validation_dataset,
    "Gaussian noise sigma 0.10"
)

Gaussian noise sigma 0.10
Images: 18000
Accuracy: 0.5014
ROC AUC: 0.5434

In [ ]:
clean_validation_auc = 0.9954998950617284

print(
    "Clean validation AUC:",
    round(clean_validation_auc, 4)
)

print(
    "Noise sigma 0.10 AUC:",
    round(noise010_result["roc_auc"], 4)
)

print(
    "AUC drop:",
    round(
        clean_validation_auc - noise010_result["roc_auc"],
        4
    )
)

Clean validation AUC: 0.9955
Noise sigma 0.10 AUC: 0.5434
AUC drop: 0.4521

In [ ]:
def create_noise_validation_dataset(sigma):
    noise_transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        AddGaussianNoise(sigma=sigma),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    return ImagePathDataset(
        all_samples,
        validation_indices,
        noise_transform
    )

In [ ]:
torch.manual_seed(2026)

noise002_result = evaluate_model(
    create_noise_validation_dataset(0.02),
    "Gaussian noise sigma 0.02"
)

Gaussian noise sigma 0.02
Images: 18000
Accuracy: 0.6641
ROC AUC: 0.8821

In [ ]:
torch.manual_seed(2026)

noise005_result = evaluate_model(
    create_noise_validation_dataset(0.05),
    "Gaussian noise sigma 0.05"
)

Gaussian noise sigma 0.05
Images: 18000
Accuracy: 0.6088
ROC AUC: 0.6642

In [ ]:
print("Gaussian-noise robustness")
print("-------------------------")
print("Clean:      ", round(clean_validation_auc, 4))
print("Sigma 0.02: ", round(noise002_result["roc_auc"], 4))
print("Sigma 0.05: ", round(noise005_result["roc_auc"], 4))
print("Sigma 0.10: ", round(noise010_result["roc_auc"], 4))

Gaussian-noise robustness
-------------------------
Clean:       0.9955
Sigma 0.02:  0.8821
Sigma 0.05:  0.6642
Sigma 0.10:  0.5434

In [ ]:
baseline_results = {
    "clean": 0.9955,
    "noise_002": 0.8821,
    "noise_005": 0.6642,
    "noise_010": 0.5434
}

model.to("cpu")
del model

if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("Model A removed from GPU. Checkpoint remains saved.")

Model A removed from GPU. Checkpoint remains saved.

In [ ]:
import random


class RandomGaussianNoise:
    def __init__(
        self,
        probability=0.5,
        sigma_choices=(0.02, 0.05, 0.10)
    ):
        self.probability = probability
        self.sigma_choices = sigma_choices

    def __call__(self, tensor):
        if random.random() >= self.probability:
            return tensor

        sigma = random.choice(self.sigma_choices)
        noise = torch.randn_like(tensor) * sigma

        return torch.clamp(
            tensor + noise,
            min=0.0,
            max=1.0
        )

In [ ]:
noise_robust_train_transform = transforms.Compose([
    transforms.RandomResizedCrop(
        224,
        scale=(0.8, 1.0)
    ),

    transforms.RandomHorizontalFlip(p=0.5),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    transforms.RandomApply(
        [
            transforms.GaussianBlur(
                kernel_size=5,
                sigma=(0.5, 2.0)
            )
        ],
        p=0.3
    ),

    transforms.ToTensor(),

    RandomGaussianNoise(
        probability=0.5,
        sigma_choices=(0.02, 0.05, 0.10)
    ),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


noise_robust_train_dataset = ImagePathDataset(
    all_samples,
    train_indices,
    noise_robust_train_transform
)


noise_robust_train_loader = DataLoader(
    noise_robust_train_dataset,
    batch_size=64,
    shuffle=True,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

print("Model B training images:", len(noise_robust_train_dataset))

Model B training images: 84000

In [ ]:
import torch.nn as nn
from torchvision import models

torch.manual_seed(2026)
random.seed(2026)
np.random.seed(2026)

weights = models.ResNet50_Weights.DEFAULT
model = models.resnet50(weights=weights)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model = model.to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=0.0001,
    weight_decay=0.0001
)

print("Model B created on:", device)

Model B created on: cuda

In [ ]:
from tqdm.auto import tqdm

model.train()

running_loss = 0.0
correct_predictions = 0
total_images = 0

progress_bar = tqdm(
    noise_robust_train_loader,
    desc="Training Model B"
)

for images, labels in progress_bar:
    images = images.to(device)
    labels = labels.to(device)

    optimizer.zero_grad(set_to_none=True)

    outputs = model(images)
    loss = criterion(outputs, labels)

    loss.backward()
    optimizer.step()

    running_loss += loss.item() * images.size(0)

    predictions = outputs.argmax(dim=1)
    correct_predictions += (
        predictions == labels
    ).sum().item()

    total_images += labels.size(0)

    progress_bar.set_postfix(
        loss=round(loss.item(), 4)
    )

model_b_training_loss = running_loss / total_images
model_b_training_accuracy = correct_predictions / total_images

print("Model B epoch completed")
print("Training loss:", model_b_training_loss)
print("Training accuracy:", model_b_training_accuracy)

Training Model B:   0%|          | 0/1313 [00:00<?, ?it/s]

Model B epoch completed
Training loss: 0.19828102569920675
Training accuracy: 0.918

In [ ]:
torch.save(
    {
        "model_state_dict": model.state_dict(),
        "class_to_idx": original_train_dataset.class_to_idx,
        "ai_class_index": AI_CLASS_INDEX,
        "training_loss": model_b_training_loss,
        "training_accuracy": model_b_training_accuracy,
        "augmentation": {
            "gaussian_noise_probability": 0.5,
            "sigma_choices": [0.02, 0.05, 0.10]
        }
    },
    "/content/resnet50_model_b_noise_epoch1.pth"
)

print("Model B checkpoint saved.")

Model B checkpoint saved.

In [ ]:
clean_validation_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

clean_validation_dataset = ImagePathDataset(
    all_samples,
    validation_indices,
    clean_validation_transform
)

model_b_clean_result = evaluate_model(
    clean_validation_dataset,
    "Model B — Clean"
)

Model B — Clean
Images: 18000
Accuracy: 0.9523
ROC AUC: 0.9933

In [ ]:
torch.manual_seed(2026)

model_b_noise002_result = evaluate_model(
    create_noise_validation_dataset(0.02),
    "Model B — Gaussian noise 0.02"
)

Model B — Gaussian noise 0.02
Images: 18000
Accuracy: 0.9653
ROC AUC: 0.9946

In [ ]:
torch.manual_seed(2026)

model_b_noise005_result = evaluate_model(
    create_noise_validation_dataset(0.05),
    "Model B — Gaussian noise 0.05"
)

Model B — Gaussian noise 0.05
Images: 18000
Accuracy: 0.9593
ROC AUC: 0.9941

In [ ]:
torch.manual_seed(2026)

model_b_noise010_result = evaluate_model(
    create_noise_validation_dataset(0.10),
    "Model B — Gaussian noise 0.10"
)

Model B — Gaussian noise 0.10
Images: 18000
Accuracy: 0.9369
ROC AUC: 0.9919

In [ ]:
comparison = {
    "Clean": (
        baseline_results["clean"],
        model_b_clean_result["roc_auc"]
    ),
    "Noise 0.02": (
        baseline_results["noise_002"],
        model_b_noise002_result["roc_auc"]
    ),
    "Noise 0.05": (
        baseline_results["noise_005"],
        model_b_noise005_result["roc_auc"]
    ),
    "Noise 0.10": (
        baseline_results["noise_010"],
        model_b_noise010_result["roc_auc"]
    )
}

print(f"{'Condition':<15} {'Model A':>10} {'Model B':>10} {'Change':>10}")
print("-" * 48)

for condition, (model_a_auc, model_b_auc) in comparison.items():
    change = model_b_auc - model_a_auc

    print(
        f"{condition:<15} "
        f"{model_a_auc:>10.4f} "
        f"{model_b_auc:>10.4f} "
        f"{change:>+10.4f}"
    )

Condition          Model A    Model B     Change
------------------------------------------------
Clean               0.9955     0.9933    -0.0022
Noise 0.02          0.8821     0.9946    +0.1125
Noise 0.05          0.6642     0.9941    +0.3299
Noise 0.10          0.5434     0.9919    +0.4485

In [ ]:
model_b_noise_mean = np.mean([
    model_b_noise002_result["roc_auc"],
    model_b_noise005_result["roc_auc"],
    model_b_noise010_result["roc_auc"]
])

print("Model B mean noise AUC:", round(model_b_noise_mean, 4))

Model B mean noise AUC: 0.9935

In [ ]:
model_b_results = {
    "clean": model_b_clean_result,
    "noise_002": model_b_noise002_result,
    "noise_005": model_b_noise005_result,
    "noise_010": model_b_noise010_result,
    "mean_noise_auc": float(model_b_noise_mean)
}

torch.save(
    {
        "model_state_dict": model.state_dict(),
        "class_to_idx": original_train_dataset.class_to_idx,
        "ai_class_index": AI_CLASS_INDEX,
        "training_loss": model_b_training_loss,
        "training_accuracy": model_b_training_accuracy,
        "augmentation": {
            "gaussian_noise_probability": 0.5,
            "sigma_choices": [0.02, 0.05, 0.10]
        },
        "validation_results": model_b_results
    },
    "/content/resnet50_model_b_noise_epoch1_evaluated.pth"
)

print("Evaluated Model B saved successfully.")

Evaluated Model B saved successfully.

In [ ]:
from google.colab import files

files.download(
    "/content/resnet50_model_b_noise_epoch1_evaluated.pth"
)

In [ ]:
model_b_blur2_result = evaluate_model(
    blur2_224_validation_dataset,
    "Model B — Gaussian blur sigma 2.0"
)

Model B — Gaussian blur sigma 2.0
Images: 18000
Accuracy: 0.9617
ROC AUC: 0.9933

In [ ]:
model_b_resize025_result = evaluate_model(
    resize025_validation_dataset,
    "Model B — Downscale 0.25x"
)

Model B — Downscale 0.25x
Images: 18000
Accuracy: 0.9009
ROC AUC: 0.9882

In [ ]:
print(f"{'Condition':<20} {'Model A':>10} {'Model B':>10} {'Change':>10}")
print("-" * 53)

cross_transform_comparison = {
    "Blur sigma 2.0": (
        0.9957,
        model_b_blur2_result["roc_auc"]
    ),
    "Resize 0.25x": (
        0.9880,
        model_b_resize025_result["roc_auc"]
    )
}

for condition, (model_a_auc, model_b_auc) in cross_transform_comparison.items():
    print(
        f"{condition:<20} "
        f"{model_a_auc:>10.4f} "
        f"{model_b_auc:>10.4f} "
        f"{model_b_auc - model_a_auc:>+10.4f}"
    )

Condition               Model A    Model B     Change
-----------------------------------------------------
Blur sigma 2.0           0.9957     0.9933    -0.0024
Resize 0.25x             0.9880     0.9882    +0.0002

In [ ]:
def create_jpeg_validation_dataset(quality):
    jpeg_transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),

        JPEGCompression(quality=quality),

        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    return ImagePathDataset(
        all_samples,
        validation_indices,
        jpeg_transform
    )

In [ ]:
model_b_jpeg_results = {}

for quality in [90, 70, 50, 30]:
    result = evaluate_model(
        create_jpeg_validation_dataset(quality),
        f"Model B — JPEG quality {quality}"
    )

    model_b_jpeg_results[quality] = result

Model B — JPEG quality 90
Images: 18000
Accuracy: 0.9574
ROC AUC: 0.9937
Model B — JPEG quality 70
Images: 18000
Accuracy: 0.9631
ROC AUC: 0.9938
Model B — JPEG quality 50
Images: 18000
Accuracy: 0.9599
ROC AUC: 0.9934
Model B — JPEG quality 30
Images: 18000
Accuracy: 0.9474
ROC AUC: 0.9922

In [ ]:
print(f"{'JPEG quality':<15} {'Accuracy':>12} {'ROC AUC':>12}")
print("-" * 41)

for quality in [90, 70, 50, 30]:
    result = model_b_jpeg_results[quality]

    print(
        f"{quality:<15} "
        f"{result['accuracy']:>12.4f} "
        f"{result['roc_auc']:>12.4f}"
    )

JPEG quality        Accuracy      ROC AUC
-----------------------------------------
90                    0.9574       0.9937
70                    0.9631       0.9938
50                    0.9599       0.9934
30                    0.9474       0.9922

In [ ]:
model_b_mean_jpeg_auc = np.mean([
    model_b_jpeg_results[quality]["roc_auc"]
    for quality in [90, 70, 50, 30]
])

print(
    "Mean JPEG ROC AUC:",
    round(model_b_mean_jpeg_auc, 4)
)

Mean JPEG ROC AUC: 0.9933

In [ ]:
def create_blur_validation_dataset(sigma):
    blur_transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),

        transforms.GaussianBlur(
            kernel_size=5,
            sigma=sigma
        ),

        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    return ImagePathDataset(
        all_samples,
        validation_indices,
        blur_transform
    )

In [ ]:
model_b_blur_results = {
    2.0: model_b_blur2_result
}

for sigma in [0.5, 1.0]:
    model_b_blur_results[sigma] = evaluate_model(
        create_blur_validation_dataset(sigma),
        f"Model B — Blur sigma {sigma}"
    )

Model B — Blur sigma 0.5
Images: 18000
Accuracy: 0.9541
ROC AUC: 0.9933
Model B — Blur sigma 1.0
Images: 18000
Accuracy: 0.9583
ROC AUC: 0.9935

In [ ]:
def create_resize_validation_dataset(scale):
    resize_transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),

        DownscaleUpscale(scale=scale),

        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    return ImagePathDataset(
        all_samples,
        validation_indices,
        resize_transform
    )

In [ ]:
model_b_resize_results = {
    0.25: model_b_resize025_result
}

model_b_resize_results[0.5] = evaluate_model(
    create_resize_validation_dataset(0.5),
    "Model B — Downscale 0.5x"
)

Model B — Downscale 0.5x
Images: 18000
Accuracy: 0.9612
ROC AUC: 0.9935

In [ ]:
class FixedColorAdjustment:
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, image):
        image = TF.adjust_brightness(image, self.factor)
        image = TF.adjust_contrast(image, self.factor)
        image = TF.adjust_saturation(image, self.factor)

        return image

In [ ]:
def create_color_validation_dataset(factor):
    color_transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),

        FixedColorAdjustment(factor=factor),

        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    return ImagePathDataset(
        all_samples,
        validation_indices,
        color_transform
    )

In [ ]:
model_b_color_results = {}

for factor, name in [(0.8, "-20%"), (1.2, "+20%")]:
    model_b_color_results[name] = evaluate_model(
        create_color_validation_dataset(factor),
        f"Model B — Colour {name}"
    )

Model B — Colour -20%
Images: 18000
Accuracy: 0.9541
ROC AUC: 0.9907
Model B — Colour +20%
Images: 18000
Accuracy: 0.9412
ROC AUC: 0.9913

In [ ]:
crop080_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),

    # Keep the central 80%: approximately 179×179
    transforms.CenterCrop(179),
    transforms.Resize((224, 224)),

    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

crop080_validation_dataset = ImagePathDataset(
    all_samples,
    validation_indices,
    crop080_transform
)

model_b_crop080_result = evaluate_model(
    crop080_validation_dataset,
    "Model B — Centre crop 80%"
)

Model B — Centre crop 80%
Images: 18000
Accuracy: 0.8699
ROC AUC: 0.9733

In [ ]:
import pandas as pd
import numpy as np

robustness_rows = [
    {
        "condition": "Clean",
        "accuracy": model_b_clean_result["accuracy"],
        "roc_auc": model_b_clean_result["roc_auc"]
    },

    {
        "condition": "JPEG quality 90",
        "accuracy": model_b_jpeg_results[90]["accuracy"],
        "roc_auc": model_b_jpeg_results[90]["roc_auc"]
    },
    {
        "condition": "JPEG quality 70",
        "accuracy": model_b_jpeg_results[70]["accuracy"],
        "roc_auc": model_b_jpeg_results[70]["roc_auc"]
    },
    {
        "condition": "JPEG quality 50",
        "accuracy": model_b_jpeg_results[50]["accuracy"],
        "roc_auc": model_b_jpeg_results[50]["roc_auc"]
    },
    {
        "condition": "JPEG quality 30",
        "accuracy": model_b_jpeg_results[30]["accuracy"],
        "roc_auc": model_b_jpeg_results[30]["roc_auc"]
    },

    {
        "condition": "Blur sigma 0.5",
        "accuracy": model_b_blur_results[0.5]["accuracy"],
        "roc_auc": model_b_blur_results[0.5]["roc_auc"]
    },
    {
        "condition": "Blur sigma 1.0",
        "accuracy": model_b_blur_results[1.0]["accuracy"],
        "roc_auc": model_b_blur_results[1.0]["roc_auc"]
    },
    {
        "condition": "Blur sigma 2.0",
        "accuracy": model_b_blur_results[2.0]["accuracy"],
        "roc_auc": model_b_blur_results[2.0]["roc_auc"]
    },

    {
        "condition": "Downscale 0.5x",
        "accuracy": model_b_resize_results[0.5]["accuracy"],
        "roc_auc": model_b_resize_results[0.5]["roc_auc"]
    },
    {
        "condition": "Downscale 0.25x",
        "accuracy": model_b_resize_results[0.25]["accuracy"],
        "roc_auc": model_b_resize_results[0.25]["roc_auc"]
    },

    {
        "condition": "Noise sigma 0.02",
        "accuracy": model_b_noise002_result["accuracy"],
        "roc_auc": model_b_noise002_result["roc_auc"]
    },
    {
        "condition": "Noise sigma 0.05",
        "accuracy": model_b_noise005_result["accuracy"],
        "roc_auc": model_b_noise005_result["roc_auc"]
    },
    {
        "condition": "Noise sigma 0.10",
        "accuracy": model_b_noise010_result["accuracy"],
        "roc_auc": model_b_noise010_result["roc_auc"]
    },

    {
        "condition": "Colour -20%",
        "accuracy": model_b_color_results["-20%"]["accuracy"],
        "roc_auc": model_b_color_results["-20%"]["roc_auc"]
    },
    {
        "condition": "Colour +20%",
        "accuracy": model_b_color_results["+20%"]["accuracy"],
        "roc_auc": model_b_color_results["+20%"]["roc_auc"]
    },

    {
        "condition": "Centre crop 80%",
        "accuracy": model_b_crop080_result["accuracy"],
        "roc_auc": model_b_crop080_result["roc_auc"]
    }
]

robustness_table = pd.DataFrame(robustness_rows)
display(robustness_table)

           condition  accuracy   roc_auc
0              Clean  0.952278  0.993255
1    JPEG quality 90  0.957444  0.993668
2    JPEG quality 70  0.963056  0.993838
3    JPEG quality 50  0.959889  0.993378
4    JPEG quality 30  0.947444  0.992243
5     Blur sigma 0.5  0.954111  0.993340
6     Blur sigma 1.0  0.958278  0.993528
7     Blur sigma 2.0  0.961667  0.993328
8     Downscale 0.5x  0.961167  0.993484
9    Downscale 0.25x  0.900889  0.988244
10  Noise sigma 0.02  0.965333  0.994604
11  Noise sigma 0.05  0.959333  0.994144
12  Noise sigma 0.10  0.936944  0.991883
13       Colour -20%  0.954056  0.990674
14       Colour +20%  0.941167  0.991294
15   Centre crop 80%  0.869889  0.973327

In [ ]:
clean_auc = robustness_table.loc[
    robustness_table["condition"] == "Clean",
    "roc_auc"
].iloc[0]

robust_auc = robustness_table.loc[
    robustness_table["condition"] != "Clean",
    "roc_auc"
].mean()

worst_row = robustness_table.loc[
    robustness_table["condition"] != "Clean"
].sort_values("roc_auc").iloc[0]

provisional_final_score = (
    0.50 * clean_auc
    + 0.50 * robust_auc
)

print("Clean AUC:", round(clean_auc, 4))
print("Mean robust AUC:", round(robust_auc, 4))
print("Provisional final score:", round(provisional_final_score, 4))
print(
    "Worst condition:",
    worst_row["condition"],
    "— AUC:",
    round(worst_row["roc_auc"], 4)
)

Clean AUC: 0.9933
Mean robust AUC: 0.9914
Provisional final score: 0.9923
Worst condition: Centre crop 80% — AUC: 0.9733

In [ ]:
robustness_table.to_csv(
    "/content/model_b_robustness_results.csv",
    index=False
)

robustness_table.to_json(
    "/content/model_b_robustness_results.json",
    orient="records",
    indent=2
)

from google.colab import files

files.download("/content/model_b_robustness_results.csv")
files.download("/content/model_b_robustness_results.json")

In [ ]:
!pip -q install -U datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 9.7 MB/s eta 0:00:00

In [ ]:
import os

print(
    "Model checkpoint exists:",
    os.path.exists(
        "/content/resnet50_model_b_noise_epoch1_evaluated.pth"
    )
)

print(
    "Training directory exists:",
    os.path.exists("/content/training")
)

Model checkpoint exists: True
Training directory exists: False

In [ ]:
import pyarrow
import datasets

print("PyArrow version:", pyarrow.__version__)
print("Datasets version:", datasets.__version__)

PyArrow version: 25.0.1
Datasets version: 5.0.1

In [ ]:
from datasets import load_dataset

sid_validation = load_dataset(
    "saberzl/SID_Set_description",
    split="validation"
)

print(sid_validation)
print("Columns:", sid_validation.column_names)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/2.50k [00:00<?, ?B/s]

data/train-00000-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  413MB

data/train-00000-of-00004.parquet: downloading bytes:           |  0.00B

data/train-00001-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  396MB

data/train-00001-of-00004.parquet: downloading bytes:           |  0.00B

data/train-00002-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  402MB

data/train-00002-of-00004.parquet: downloading bytes:           |  0.00B

data/train-00003-of-00004.parquet: reconstructing file:   0%|          |  0.00B /  400MB

data/train-00003-of-00004.parquet: downloading bytes:           |  0.00B

data/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  177MB

data/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/2700 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/300 [00:00<?, ? examples/s]

Dataset({
    features: ['image', 'label', 'description', 'mask'],
    num_rows: 300
})
Columns: ['image', 'label', 'description', 'mask']

In [ ]:
import os
import torch
import torch.nn as nn
import numpy as np

from torchvision import models, transforms

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

checkpoint_path = (
    "/content/resnet50_model_b_noise_epoch1_evaluated.pth"
)

print("Device:", device)
print("Checkpoint exists:", os.path.exists(checkpoint_path))

Device: cuda
Checkpoint exists: True

In [ ]:
checkpoint = torch.load(
    checkpoint_path,
    map_location=device,
    weights_only=False
)

model = models.resnet50(weights=None)

model.fc = nn.Linear(
    model.fc.in_features,
    2
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

model = model.to(device)
model.eval()

AI_CLASS_INDEX = checkpoint["ai_class_index"]

print("Model restored successfully")
print("Class mapping:", checkpoint["class_to_idx"])
print("AI class index:", AI_CLASS_INDEX)

Model restored successfully
Class mapping: {'FAKE': 0, 'REAL': 1}
AI class index: 0

In [ ]:
from datasets import load_dataset
from collections import Counter

sid_validation = load_dataset(
    "saberzl/SID_Set_description",
    split="validation"
)

print(sid_validation)

print(
    "Original SID labels:",
    Counter(sid_validation["label"])
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Dataset({
    features: ['image', 'label', 'description', 'mask'],
    num_rows: 300
})
Original SID labels: Counter({0: 100, 1: 100, 2: 100})

In [ ]:
from collections import Counter
from torch.utils.data import Dataset, DataLoader

print(
    "Original SID labels:",
    Counter(sid_validation["label"])
)

Original SID labels: Counter({0: 100, 1: 100, 2: 100})

In [ ]:
sid_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [ ]:
class SIDBinaryDataset(Dataset):
    def __init__(self, huggingface_dataset, transform):
        self.dataset = huggingface_dataset
        self.transform = transform

        self.indices = [
            index
            for index, label
            in enumerate(huggingface_dataset["label"])
            if label in [0, 1]
        ]

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, position):
        dataset_index = self.indices[position]
        example = self.dataset[dataset_index]

        image = example["image"].convert("RGB")
        sid_label = example["label"]

        # Evaluation convention:
        # 0 = real
        # 1 = AI-generated
        binary_ai_label = 1 if sid_label == 1 else 0

        image = self.transform(image)

        return image, binary_ai_label


sid_binary_dataset = SIDBinaryDataset(
    sid_validation,
    sid_transform
)

sid_loader = DataLoader(
    sid_binary_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

print("Binary SID images:", len(sid_binary_dataset))

Binary SID images: 200

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    confusion_matrix
)

sid_labels = []
sid_ai_probabilities = []

model.eval()

with torch.no_grad():
    for images, labels in sid_loader:
        images = images.to(device)

        outputs = model(images)
        probabilities = torch.softmax(outputs, dim=1)

        ai_probabilities = probabilities[:, AI_CLASS_INDEX]

        sid_labels.extend(labels.numpy())
        sid_ai_probabilities.extend(
            ai_probabilities.cpu().numpy()
        )

sid_labels = np.array(sid_labels)
sid_ai_probabilities = np.array(sid_ai_probabilities)

sid_predictions = (
    sid_ai_probabilities >= 0.5
).astype(int)

sid_accuracy = accuracy_score(
    sid_labels,
    sid_predictions
)

sid_roc_auc = roc_auc_score(
    sid_labels,
    sid_ai_probabilities
)

sid_confusion_matrix = confusion_matrix(
    sid_labels,
    sid_predictions
)

print("External SID images:", len(sid_labels))
print("External SID accuracy:", round(sid_accuracy, 4))
print("External SID ROC AUC:", round(sid_roc_auc, 4))

print()
print("Confusion matrix:")
print(sid_confusion_matrix)

print()
print(
    "Mean AI confidence for real images:",
    round(
        sid_ai_probabilities[sid_labels == 0].mean(),
        4
    )
)

print(
    "Mean AI confidence for synthetic images:",
    round(
        sid_ai_probabilities[sid_labels == 1].mean(),
        4
    )
)

External SID images: 200
External SID accuracy: 0.505
External SID ROC AUC: 0.8114

Confusion matrix:
[[  1  99]
 [  0 100]]

Mean AI confidence for real images: 0.9828
Mean AI confidence for synthetic images: 0.9983

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_curve,
    roc_auc_score,
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix
)

all_sid_indices = np.arange(len(sid_labels))

calibration_indices, holdout_indices = train_test_split(
    all_sid_indices,
    test_size=0.5,
    random_state=2026,
    stratify=sid_labels
)

print("Calibration images:", len(calibration_indices))
print("Untouched holdout images:", len(holdout_indices))

Calibration images: 100
Untouched holdout images: 100

In [ ]:
calibration_labels = sid_labels[calibration_indices]
calibration_probabilities = sid_ai_probabilities[
    calibration_indices
]

fpr, tpr, thresholds = roc_curve(
    calibration_labels,
    calibration_probabilities
)

youden_j = tpr - fpr
best_position = np.argmax(youden_j)
calibrated_threshold = float(thresholds[best_position])

print(
    "Threshold learned from calibration half:",
    calibrated_threshold
)

Threshold learned from calibration half: 0.9991313815116882

In [ ]:
holdout_labels = sid_labels[holdout_indices]
holdout_probabilities = sid_ai_probabilities[
    holdout_indices
]

holdout_predictions = (
    holdout_probabilities >= calibrated_threshold
).astype(int)

holdout_accuracy = accuracy_score(
    holdout_labels,
    holdout_predictions
)

holdout_balanced_accuracy = balanced_accuracy_score(
    holdout_labels,
    holdout_predictions
)

holdout_auc = roc_auc_score(
    holdout_labels,
    holdout_probabilities
)

holdout_matrix = confusion_matrix(
    holdout_labels,
    holdout_predictions
)

print("SID holdout ROC AUC:", round(holdout_auc, 4))
print("SID holdout accuracy:", round(holdout_accuracy, 4))
print(
    "SID holdout balanced accuracy:",
    round(holdout_balanced_accuracy, 4)
)

print()
print("SID holdout confusion matrix:")
print(holdout_matrix)

SID holdout ROC AUC: 0.8434
SID holdout accuracy: 0.78
SID holdout balanced accuracy: 0.78

SID holdout confusion matrix:
[[40 10]
 [12 38]]

In [ ]:
import json

sid_zero_shot_results = {
    "total_external_images": int(len(sid_labels)),
    "full_external_auc": float(sid_roc_auc),
    "default_threshold_accuracy": float(sid_accuracy),
    "calibrated_threshold": float(calibrated_threshold),
    "holdout_images": int(len(holdout_labels)),
    "holdout_auc": float(holdout_auc),
    "holdout_accuracy": float(holdout_accuracy),
    "holdout_balanced_accuracy": float(
        holdout_balanced_accuracy
    ),
    "holdout_confusion_matrix": (
        holdout_matrix.tolist()
    )
}

with open(
    "/content/model_b_sid_zero_shot_results.json",
    "w"
) as file:
    json.dump(
        sid_zero_shot_results,
        file,
        indent=2
    )

print("Zero-shot SID results saved.")

Zero-shot SID results saved.

In [ ]:
sid_train = load_dataset(
    "saberzl/SID_Set_description",
    split="train"
)

print(sid_train)

print(
    "SID training labels:",
    Counter(sid_train["label"])
)

Dataset({
    features: ['image', 'label', 'description', 'mask'],
    num_rows: 2700
})
SID training labels: Counter({1: 900, 2: 900, 0: 900})

In [ ]:
sid_binary_train_indices = [
    index
    for index, label in enumerate(sid_train["label"])
    if label in [0, 1]
]

sid_binary_train_labels = [
    sid_train[index]["label"]
    for index in sid_binary_train_indices
]

print(
    "Selected binary training images:",
    len(sid_binary_train_indices)
)

print(
    "Selected label counts:",
    Counter(sid_binary_train_labels)
)

Selected binary training images: 1800
Selected label counts: Counter({1: 900, 0: 900})

In [ ]:
import random


class RandomGaussianNoise:
    def __init__(
        self,
        probability=0.5,
        sigma_choices=(0.02, 0.05, 0.10)
    ):
        self.probability = probability
        self.sigma_choices = sigma_choices

    def __call__(self, tensor):
        if random.random() >= self.probability:
            return tensor

        sigma = random.choice(self.sigma_choices)
        noise = torch.randn_like(tensor) * sigma

        return torch.clamp(
            tensor + noise,
            min=0.0,
            max=1.0
        )

In [ ]:
sid_train_transform = transforms.Compose([
    # Randomly crop the high-resolution image and output 224×224
    transforms.RandomResizedCrop(
        224,
        scale=(0.8, 1.0)
    ),

    # Sometimes mirror the image
    transforms.RandomHorizontalFlip(p=0.5),

    # Simulate colour changes
    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    # Sometimes simulate blur
    transforms.RandomApply(
        [
            transforms.GaussianBlur(
                kernel_size=5,
                sigma=(0.5, 2.0)
            )
        ],
        p=0.3
    ),

    # Convert the image into model-readable numbers
    transforms.ToTensor(),

    # Sometimes add one of the official noise levels
    RandomGaussianNoise(
        probability=0.5,
        sigma_choices=(0.02, 0.05, 0.10)
    ),

    # Apply the normal ResNet50 input normalisation
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [ ]:
from torch.utils.data import Dataset, DataLoader


REAL_CLASS_INDEX = checkpoint["class_to_idx"]["REAL"]


class SIDTrainingDataset(Dataset):
    def __init__(self, huggingface_dataset, transform):
        self.dataset = huggingface_dataset
        self.transform = transform

        self.indices = [
            index
            for index, label
            in enumerate(huggingface_dataset["label"])
            if label in [0, 1]
        ]

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, position):
        dataset_index = self.indices[position]
        example = self.dataset[dataset_index]

        image = example["image"].convert("RGB")
        sid_label = example["label"]

        if sid_label == 1:
            model_label = AI_CLASS_INDEX
        else:
            model_label = REAL_CLASS_INDEX

        image = self.transform(image)

        return image, model_label


sid_training_dataset = SIDTrainingDataset(
    sid_train,
    sid_train_transform
)

sid_training_loader = DataLoader(
    sid_training_dataset,
    batch_size=32,
    shuffle=True,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

print("Model B-HR training images:", len(sid_training_dataset))
print("AI output index:", AI_CLASS_INDEX)
print("Real output index:", REAL_CLASS_INDEX)

Model B-HR training images: 1800
AI output index: 0
Real output index: 1

In [ ]:
# Freeze the entire model
for parameter in model.parameters():
    parameter.requires_grad = False

# Allow the final ResNet block to adapt
for parameter in model.layer4.parameters():
    parameter.requires_grad = True

# Allow the classifier to adapt
for parameter in model.fc.parameters():
    parameter.requires_grad = True

trainable_parameters = sum(
    parameter.numel()
    for parameter in model.parameters()
    if parameter.requires_grad
)

total_parameters = sum(
    parameter.numel()
    for parameter in model.parameters()
)

print("Trainable parameters:", trainable_parameters)
print("Total parameters:", total_parameters)
print(
    "Trainable percentage:",
    round(100 * trainable_parameters / total_parameters, 2),
    "%"
)

Trainable parameters: 14968834
Total parameters: 23512130
Trainable percentage: 63.66 %

In [ ]:
import torch.nn as nn

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    [
        {
            "params": model.layer4.parameters(),
            "lr": 0.00001
        },
        {
            "params": model.fc.parameters(),
            "lr": 0.00005
        }
    ],
    weight_decay=0.0001
)

In [ ]:
from sklearn.metrics import accuracy_score, roc_auc_score


def evaluate_sid_model(model, loader):
    model.eval()

    evaluation_labels = []
    evaluation_probabilities = []

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device)

            outputs = model(images)
            probabilities = torch.softmax(
                outputs,
                dim=1
            )

            ai_probabilities = probabilities[
                :,
                AI_CLASS_INDEX
            ]

            evaluation_labels.extend(
                labels.numpy()
            )

            evaluation_probabilities.extend(
                ai_probabilities.cpu().numpy()
            )

    evaluation_labels = np.array(evaluation_labels)
    evaluation_probabilities = np.array(
        evaluation_probabilities
    )

    predictions = (
        evaluation_probabilities >= 0.5
    ).astype(int)

    return {
        "accuracy": float(
            accuracy_score(
                evaluation_labels,
                predictions
            )
        ),
        "roc_auc": float(
            roc_auc_score(
                evaluation_labels,
                evaluation_probabilities
            )
        )
    }

In [ ]:
from tqdm.auto import tqdm

best_sid_auc = 0.0
best_epoch = 0

training_history = []

for epoch in range(1, 4):
    # Keep frozen sections in evaluation mode.
    # Train only layer4 and the classifier.
    model.eval()
    model.layer4.train()
    model.fc.train()

    running_loss = 0.0
    correct_predictions = 0
    total_images = 0

    progress_bar = tqdm(
        sid_training_loader,
        desc=f"Model B-HR epoch {epoch}/3"
    )

    for images, labels in progress_bar:
        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad(set_to_none=True)

        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        running_loss += (
            loss.item() * images.size(0)
        )

        predictions = outputs.argmax(dim=1)

        correct_predictions += (
            predictions == labels
        ).sum().item()

        total_images += labels.size(0)

        progress_bar.set_postfix(
            loss=round(loss.item(), 4)
        )

    training_loss = running_loss / total_images
    training_accuracy = (
        correct_predictions / total_images
    )

    validation_result = evaluate_sid_model(
        model,
        sid_loader
    )

    epoch_result = {
        "epoch": epoch,
        "training_loss": training_loss,
        "training_accuracy": training_accuracy,
        "sid_validation_accuracy": (
            validation_result["accuracy"]
        ),
        "sid_validation_auc": (
            validation_result["roc_auc"]
        )
    }

    training_history.append(epoch_result)

    print()
    print("Epoch:", epoch)
    print("Training loss:", round(training_loss, 4))
    print(
        "Training accuracy:",
        round(training_accuracy, 4)
    )
    print(
        "SID validation accuracy:",
        round(validation_result["accuracy"], 4)
    )
    print(
        "SID validation ROC AUC:",
        round(validation_result["roc_auc"], 4)
    )

    if validation_result["roc_auc"] > best_sid_auc:
        best_sid_auc = validation_result["roc_auc"]
        best_epoch = epoch

        torch.save(
            {
                "model_state_dict": model.state_dict(),
                "class_to_idx": checkpoint["class_to_idx"],
                "ai_class_index": AI_CLASS_INDEX,
                "experiment": "Model B-HR",
                "best_epoch": best_epoch,
                "sid_validation_auc": best_sid_auc,
                "training_history": training_history
            },
            "/content/resnet50_model_b_hr_best.pth"
        )

        print("New best Model B-HR saved.")

    print("-" * 50)

print("Best epoch:", best_epoch)
print("Best SID validation AUC:", round(best_sid_auc, 4))

Model B-HR epoch 1/3:   0%|          | 0/57 [00:00<?, ?it/s]

Epoch: 1
Training loss: 0.7417
Training accuracy: 0.67
SID validation accuracy: 0.765
SID validation ROC AUC: 0.8375
New best Model B-HR saved.
--------------------------------------------------

Model B-HR epoch 2/3:   0%|          | 0/57 [00:00<?, ?it/s]

Epoch: 2
Training loss: 0.5884
Training accuracy: 0.7172
SID validation accuracy: 0.785
SID validation ROC AUC: 0.8551
New best Model B-HR saved.
--------------------------------------------------

Model B-HR epoch 3/3:   0%|          | 0/57 [00:00<?, ?it/s]

Epoch: 3
Training loss: 0.5414
Training accuracy: 0.7256
SID validation accuracy: 0.79
SID validation ROC AUC: 0.8794
New best Model B-HR saved.
--------------------------------------------------
Best epoch: 3
Best SID validation AUC: 0.8794

In [ ]:
from google.colab import files

files.download(
    "/content/resnet50_model_b_hr_best.pth"
)

In [ ]:
best_hr_checkpoint = torch.load(
    "/content/resnet50_model_b_hr_best.pth",
    map_location=device,
    weights_only=False
)

model.load_state_dict(
    best_hr_checkpoint["model_state_dict"]
)

model.eval()

print(
    "Restored best Model B-HR from epoch:",
    best_hr_checkpoint["best_epoch"]
)

Restored best Model B-HR from epoch: 3

In [ ]:
!git clone --depth 1 \
https://github.com/koowenqi/TechJam-Ctrl-Alt-Elite.git \
/content/techjam_repo_restore

Cloning into '/content/techjam_repo_restore'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 0), reused 4 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.

In [ ]:
from pathlib import Path

archive_candidates = list(
    Path("/content/techjam_repo_restore").rglob(
        "archive.zip"
    )
)

print("Archives found:", archive_candidates)

Archives found: [PosixPath('/content/techjam_repo_restore/archive.zip')]

In [ ]:
archive_path = str(archive_candidates[0])

!mkdir -p /content/training
!unzip -q "$archive_path" -d /content/training

print("Extraction completed.")

Extraction completed.

In [ ]:
from pathlib import Path

for folder in Path("/content/training").rglob("*"):
    if folder.is_dir():
        print(folder)

/content/training/test
/content/training/train
/content/training/test/REAL
/content/training/test/FAKE
/content/training/train/REAL
/content/training/train/FAKE

In [ ]:
%cd /content/techjam_repo_restore

!git lfs install
!git lfs pull

/content/techjam_repo_restore
Updated Git hooks.
Git LFS initialized.

In [ ]:
!mkdir -p /content/training
!unzip -q "/content/archive.zip" -d /content/training

unzip:  cannot find or open /content/archive.zip, /content/archive.zip.zip or /content/archive.zip.ZIP.

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving archive.zip to archive (1).zip

In [ ]:
!mkdir -p /content/training
!unzip -q "/content/archive.zip" -d /content/training

unzip:  cannot find or open /content/archive.zip, /content/archive.zip.zip or /content/archive.zip.ZIP.

In [ ]:
from pathlib import Path

zip_files = list(
    Path("/content").rglob("*.zip")
)

print("ZIP files found:")

for zip_file in zip_files:
    print(zip_file)

ZIP files found:
/content/TechJam-Ctrl-Alt-Elite/archive.zip
/content/techjam_repo_restore/archive (1).zip
/content/techjam_repo_restore/archive.zip

In [ ]:
!mkdir -p /content/training
!unzip -q "$archive_path" -d /content/training

print("Extraction finished.")

replace /content/training/test/FAKE/0 (10).jpg? [y]es, [n]o, [A]ll, [N]one, [r]ename: Extraction finished.

In [ ]:
required_folders = [
    Path("/content/training/train/FAKE"),
    Path("/content/training/train/REAL"),
    Path("/content/training/test/FAKE"),
    Path("/content/training/test/REAL")
]

for folder in required_folders:
    print(folder, "exists:", folder.exists())

/content/training/train/FAKE exists: True
/content/training/train/REAL exists: True
/content/training/test/FAKE exists: True
/content/training/test/REAL exists: True

In [ ]:
original_train_dataset = datasets.ImageFolder(
    Path("/content/training/train")
)

original_test_dataset = datasets.ImageFolder(
    Path("/content/training/test")
)

In [ ]:
import numpy as np
import torch

from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, roc_auc_score


def evaluate_cifake(model, dataset, name):
    loader = DataLoader(
        dataset,
        batch_size=64,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

    model.eval()

    labels_list = []
    probabilities_list = []

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(device)

            outputs = model(images)

            probabilities = torch.softmax(
                outputs,
                dim=1
            )

            ai_probabilities = probabilities[
                :,
                AI_CLASS_INDEX
            ]

            labels_list.extend(
                labels.cpu().numpy()
            )

            probabilities_list.extend(
                ai_probabilities.cpu().numpy()
            )

    labels_array = np.array(labels_list)
    probabilities_array = np.array(
        probabilities_list
    )

    binary_ai_labels = (
        labels_array == AI_CLASS_INDEX
    ).astype(int)

    predicted_ai_labels = (
        probabilities_array >= 0.5
    ).astype(int)

    result = {
        "accuracy": float(
            accuracy_score(
                binary_ai_labels,
                predicted_ai_labels
            )
        ),
        "roc_auc": float(
            roc_auc_score(
                binary_ai_labels,
                probabilities_array
            )
        )
    }

    print(name)
    print("Images:", len(labels_array))
    print("Accuracy:", round(result["accuracy"], 4))
    print("ROC AUC:", round(result["roc_auc"], 4))

    return result

In [ ]:
from pathlib import Path
from PIL import Image

import numpy as np
import torch

from torchvision import datasets, transforms
from torch.utils.data import Dataset
from sklearn.model_selection import train_test_split


# 1. Confirm CIFAKE folders exist

train_path = Path("/content/training/train")
test_path = Path("/content/training/test")

assert train_path.exists(), f"Missing: {train_path}"
assert test_path.exists(), f"Missing: {test_path}"

print("CIFAKE folders found.")


# 2. Read the original archive folders

original_train_dataset = datasets.ImageFolder(
    train_path
)

original_test_dataset = datasets.ImageFolder(
    test_path
)

assert (
    original_train_dataset.class_to_idx
    == original_test_dataset.class_to_idx
)

print(
    "Class mapping:",
    original_train_dataset.class_to_idx
)


# 3. Combine the original train and test samples

all_samples = (
    original_train_dataset.samples
    + original_test_dataset.samples
)

source_labels = np.array([
    label for _, label in all_samples
])

all_indices = np.arange(len(all_samples))


# 4. Recreate the exact 70/15/15 split

train_indices, remaining_indices = train_test_split(
    all_indices,
    test_size=0.30,
    random_state=2026,
    stratify=source_labels
)

validation_indices, test_indices = train_test_split(
    remaining_indices,
    test_size=0.50,
    random_state=2026,
    stratify=source_labels[remaining_indices]
)

print("Training images:", len(train_indices))
print("Validation images:", len(validation_indices))
print("Test images:", len(test_indices))


# 5. Define the image-loading dataset

class CIFAKEPathDataset(Dataset):
    def __init__(self, samples, indices, transform):
        self.samples = samples
        self.indices = indices
        self.transform = transform

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, position):
        sample_index = self.indices[position]
        image_path, label = self.samples[sample_index]

        image = Image.open(image_path).convert("RGB")
        image = self.transform(image)

        return image, label


# 6. Define clean ResNet preprocessing

cifake_clean_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


# 7. Create the missing validation dataset

cifake_validation_dataset = CIFAKEPathDataset(
    all_samples,
    validation_indices,
    cifake_clean_transform
)

print(
    "CIFAKE validation dataset created:",
    len(cifake_validation_dataset)
)

CIFAKE folders found.
Class mapping: {'FAKE': 0, 'REAL': 1}
Training images: 84000
Validation images: 18000
Test images: 18000
CIFAKE validation dataset created: 18000

In [ ]:
model_b_hr_cifake_clean = evaluate_cifake(
    model,
    cifake_validation_dataset,
    "Model B-HR — CIFAKE clean regression"
)

print()
print("Previous Model B clean AUC: 0.9933")

print(
    "Model B-HR clean AUC:",
    round(model_b_hr_cifake_clean["roc_auc"], 4)
)

print(
    "AUC change:",
    round(
        model_b_hr_cifake_clean["roc_auc"] - 0.9933,
        4
    )
)

Model B-HR — CIFAKE clean regression
Images: 18000
Accuracy: 0.5729
ROC AUC: 0.9742

Previous Model B clean AUC: 0.9933
Model B-HR clean AUC: 0.9742
AUC change: -0.0191

In [ ]:
cifake_replay_indices, _ = train_test_split(
    train_indices,
    train_size=1800,
    random_state=2026,
    stratify=source_labels[train_indices]
)

print("CIFAKE replay images:", len(cifake_replay_indices))

print(
    "CIFAKE replay class counts:",
    Counter(source_labels[cifake_replay_indices])
)

CIFAKE replay images: 1800
CIFAKE replay class counts: Counter({np.int64(0): 900, np.int64(1): 900})

In [ ]:
cifake_replay_dataset = CIFAKEPathDataset(
    all_samples,
    cifake_replay_indices,
    sid_train_transform
)

In [ ]:
from torch.utils.data import ConcatDataset

mixed_training_dataset = ConcatDataset([
    sid_training_dataset,
    cifake_replay_dataset
])

mixed_training_loader = DataLoader(
    mixed_training_dataset,
    batch_size=32,
    shuffle=True,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

print("SID training images:", len(sid_training_dataset))
print("CIFAKE replay images:", len(cifake_replay_dataset))
print("Combined images:", len(mixed_training_dataset))

SID training images: 1800
CIFAKE replay images: 1800
Combined images: 3600

In [ ]:
# The SID-only model is already saved and downloaded.
model.to("cpu")

if torch.cuda.is_available():
    torch.cuda.empty_cache()

mixed_model = models.resnet50(weights=None)

mixed_model.fc = nn.Linear(
    mixed_model.fc.in_features,
    2
)

mixed_model.load_state_dict(
    checkpoint["model_state_dict"]
)

mixed_model = mixed_model.to(device)

for parameter in mixed_model.parameters():
    parameter.requires_grad = False

for parameter in mixed_model.layer4.parameters():
    parameter.requires_grad = True

for parameter in mixed_model.fc.parameters():
    parameter.requires_grad = True

print("Original Model B restored for mixed training.")

Original Model B restored for mixed training.

In [ ]:
mixed_optimizer = torch.optim.AdamW(
    [
        {
            "params": mixed_model.layer4.parameters(),
            "lr": 0.00001
        },
        {
            "params": mixed_model.fc.parameters(),
            "lr": 0.00005
        }
    ],
    weight_decay=0.0001
)

mixed_history = []
best_mixed_score = 0.0
best_mixed_epoch = 0

for epoch in range(1, 4):
    mixed_model.eval()
    mixed_model.layer4.train()
    mixed_model.fc.train()

    running_loss = 0.0
    correct = 0
    total = 0

    progress_bar = tqdm(
        mixed_training_loader,
        desc=f"Model B-Mix epoch {epoch}/3"
    )

    for images, labels in progress_bar:
        images = images.to(device)
        labels = labels.to(device)

        mixed_optimizer.zero_grad(set_to_none=True)

        outputs = mixed_model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        mixed_optimizer.step()

        running_loss += loss.item() * images.size(0)

        predictions = outputs.argmax(dim=1)
        correct += (
            predictions == labels
        ).sum().item()

        total += labels.size(0)

        progress_bar.set_postfix(
            loss=round(loss.item(), 4)
        )

    training_loss = running_loss / total
    training_accuracy = correct / total

    sid_result = evaluate_sid_model(
        mixed_model,
        sid_loader
    )

    cifake_result = evaluate_cifake(
        mixed_model,
        cifake_validation_dataset,
        f"Epoch {epoch} — CIFAKE validation"
    )

    # Select a model that performs well on both sources
    selection_score = (
        sid_result["roc_auc"]
        + cifake_result["roc_auc"]
    ) / 2

    epoch_result = {
        "epoch": epoch,
        "training_loss": training_loss,
        "training_accuracy": training_accuracy,
        "sid_auc": sid_result["roc_auc"],
        "cifake_auc": cifake_result["roc_auc"],
        "mean_auc": selection_score
    }

    mixed_history.append(epoch_result)

    print("Epoch:", epoch)
    print("Training loss:", round(training_loss, 4))
    print("Training accuracy:", round(training_accuracy, 4))
    print("SID AUC:", round(sid_result["roc_auc"], 4))
    print("CIFAKE AUC:", round(cifake_result["roc_auc"], 4))
    print("Mean AUC:", round(selection_score, 4))

    if selection_score > best_mixed_score:
        best_mixed_score = selection_score
        best_mixed_epoch = epoch

        torch.save(
            {
                "model_state_dict": mixed_model.state_dict(),
                "class_to_idx": checkpoint["class_to_idx"],
                "ai_class_index": AI_CLASS_INDEX,
                "experiment": "Model B-Mix",
                "best_epoch": best_mixed_epoch,
                "selection_score": best_mixed_score,
                "training_history": mixed_history
            },
            "/content/resnet50_model_b_mix_best.pth"
        )

        print("New best Model B-Mix saved.")

    print("-" * 50)

print("Best mixed epoch:", best_mixed_epoch)
print("Best mean AUC:", round(best_mixed_score, 4))

Model B-Mix epoch 1/3:   0%|          | 0/113 [00:00<?, ?it/s]

Epoch 1 — CIFAKE validation
Images: 18000
Accuracy: 0.954
ROC AUC: 0.9912
Epoch: 1
Training loss: 0.5134
Training accuracy: 0.7783
SID AUC: 0.8258
CIFAKE AUC: 0.9912
Mean AUC: 0.9085
New best Model B-Mix saved.
--------------------------------------------------

Model B-Mix epoch 2/3:   0%|          | 0/113 [00:00<?, ?it/s]

Epoch 2 — CIFAKE validation
Images: 18000
Accuracy: 0.956
ROC AUC: 0.9915
Epoch: 2
Training loss: 0.3682
Training accuracy: 0.8225
SID AUC: 0.8665
CIFAKE AUC: 0.9915
Mean AUC: 0.929
New best Model B-Mix saved.
--------------------------------------------------

Model B-Mix epoch 3/3:   0%|          | 0/113 [00:00<?, ?it/s]

Epoch 3 — CIFAKE validation
Images: 18000
Accuracy: 0.955
ROC AUC: 0.9912
Epoch: 3
Training loss: 0.332
Training accuracy: 0.8403
SID AUC: 0.9057
CIFAKE AUC: 0.9912
Mean AUC: 0.9484
New best Model B-Mix saved.
--------------------------------------------------
Best mixed epoch: 3
Best mean AUC: 0.9484

In [ ]:
from google.colab import files

files.download(
    "/content/resnet50_model_b_mix_best.pth"
)

In [ ]:
best_mix_checkpoint = torch.load(
    "/content/resnet50_model_b_mix_best.pth",
    map_location=device,
    weights_only=False
)

mixed_model.load_state_dict(
    best_mix_checkpoint["model_state_dict"]
)

mixed_model.eval()

print(
    "Loaded Model B-Mix epoch:",
    best_mix_checkpoint["best_epoch"]
)

Loaded Model B-Mix epoch: 3

In [ ]:
class FixedGaussianNoise:
    def __init__(self, sigma):
        self.sigma = sigma

    def __call__(self, tensor):
        noise = torch.randn_like(tensor) * self.sigma

        return torch.clamp(
            tensor + noise,
            min=0.0,
            max=1.0
        )

In [ ]:
sid_noise010_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),

    FixedGaussianNoise(sigma=0.10),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

sid_noise010_dataset = SIDBinaryDataset(
    sid_validation,
    sid_noise010_transform
)

sid_noise010_loader = DataLoader(
    sid_noise010_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

In [ ]:
torch.manual_seed(2026)

model_b_mix_sid_noise010 = evaluate_sid_model(
    mixed_model,
    sid_noise010_loader
)

print("Model B-Mix — SID noise sigma 0.10")
print(
    "Accuracy:",
    round(model_b_mix_sid_noise010["accuracy"], 4)
)
print(
    "ROC AUC:",
    round(model_b_mix_sid_noise010["roc_auc"], 4)
)

print()
print("Clean SID AUC: 0.9057")
print(
    "Noise AUC drop:",
    round(
        0.9057
        - model_b_mix_sid_noise010["roc_auc"],
        4
    )
)

Model B-Mix — SID noise sigma 0.10
Accuracy: 0.75
ROC AUC: 0.831

Clean SID AUC: 0.9057
Noise AUC drop: 0.0747

In [ ]:
def create_sid_noise_loader(sigma):
    noise_transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),

        FixedGaussianNoise(sigma=sigma),

        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    dataset = SIDBinaryDataset(
        sid_validation,
        noise_transform
    )

    return DataLoader(
        dataset,
        batch_size=32,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

In [ ]:
torch.manual_seed(2026)

model_b_mix_sid_noise002 = evaluate_sid_model(
    mixed_model,
    create_sid_noise_loader(0.02)
)

print(
    "SID noise 0.02 AUC:",
    round(model_b_mix_sid_noise002["roc_auc"], 4)
)

SID noise 0.02 AUC: 0.8837

In [ ]:
torch.manual_seed(2026)

model_b_mix_sid_noise005 = evaluate_sid_model(
    mixed_model,
    create_sid_noise_loader(0.05)
)

print(
    "SID noise 0.05 AUC:",
    round(model_b_mix_sid_noise005["roc_auc"], 4)
)

SID noise 0.05 AUC: 0.8651

In [ ]:
print("Model B-Mix — SID noise robustness")
print("----------------------------------")
print("Clean:      ", round(0.9057, 4))
print(
    "Sigma 0.02: ",
    round(model_b_mix_sid_noise002["roc_auc"], 4)
)
print(
    "Sigma 0.05: ",
    round(model_b_mix_sid_noise005["roc_auc"], 4)
)
print(
    "Sigma 0.10: ",
    round(model_b_mix_sid_noise010["roc_auc"], 4)
)

Model B-Mix — SID noise robustness
----------------------------------
Clean:       0.9057
Sigma 0.02:  0.8837
Sigma 0.05:  0.8651
Sigma 0.10:  0.831

In [ ]:
sid_crop080_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),

    # Keep the central 80% of 224×224
    transforms.CenterCrop(179),

    # Enlarge the crop back to the model's input size
    transforms.Resize((224, 224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

sid_crop080_dataset = SIDBinaryDataset(
    sid_validation,
    sid_crop080_transform
)

sid_crop080_loader = DataLoader(
    sid_crop080_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

model_b_mix_sid_crop080 = evaluate_sid_model(
    mixed_model,
    sid_crop080_loader
)

print("Model B-Mix — SID centre crop 80%")
print(
    "Accuracy:",
    round(model_b_mix_sid_crop080["accuracy"], 4)
)
print(
    "ROC AUC:",
    round(model_b_mix_sid_crop080["roc_auc"], 4)
)
print(
    "AUC drop:",
    round(
        0.9057
        - model_b_mix_sid_crop080["roc_auc"],
        4
    )
)

Model B-Mix — SID centre crop 80%
Accuracy: 0.815
ROC AUC: 0.8906
AUC drop: 0.0151

In [ ]:
import io
from PIL import Image


class JPEGCompression:
    def __init__(self, quality):
        self.quality = quality

    def __call__(self, image):
        buffer = io.BytesIO()

        image.save(
            buffer,
            format="JPEG",
            quality=self.quality
        )

        buffer.seek(0)

        compressed_image = Image.open(
            buffer
        ).convert("RGB")

        compressed_image.load()

        return compressed_image

In [ ]:
sid_jpeg30_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),

    JPEGCompression(quality=30),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

sid_jpeg30_dataset = SIDBinaryDataset(
    sid_validation,
    sid_jpeg30_transform
)

sid_jpeg30_loader = DataLoader(
    sid_jpeg30_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

model_b_mix_sid_jpeg30 = evaluate_sid_model(
    mixed_model,
    sid_jpeg30_loader
)

print("Model B-Mix — SID JPEG quality 30")
print(
    "Accuracy:",
    round(model_b_mix_sid_jpeg30["accuracy"], 4)
)
print(
    "ROC AUC:",
    round(model_b_mix_sid_jpeg30["roc_auc"], 4)
)
print(
    "AUC drop:",
    round(
        0.9057
        - model_b_mix_sid_jpeg30["roc_auc"],
        4
    )
)

Model B-Mix — SID JPEG quality 30
Accuracy: 0.795
ROC AUC: 0.8635
AUC drop: 0.0422

In [ ]:
sid_blur2_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),

    transforms.GaussianBlur(
        kernel_size=5,
        sigma=2.0
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

sid_blur2_loader = DataLoader(
    SIDBinaryDataset(
        sid_validation,
        sid_blur2_transform
    ),
    batch_size=32,
    shuffle=False,
    num_workers=0
)

model_b_mix_sid_blur2 = evaluate_sid_model(
    mixed_model,
    sid_blur2_loader
)

In [ ]:
from torchvision.transforms import functional as TF
from torchvision.transforms import InterpolationMode


class DownscaleUpscale:
    def __init__(self, scale):
        self.scale = scale

    def __call__(self, image):
        width, height = image.size

        small_width = max(
            1,
            int(width * self.scale)
        )

        small_height = max(
            1,
            int(height * self.scale)
        )

        image = TF.resize(
            image,
            [small_height, small_width],
            interpolation=InterpolationMode.BILINEAR
        )

        image = TF.resize(
            image,
            [height, width],
            interpolation=InterpolationMode.BILINEAR
        )

        return image

In [ ]:
sid_resize025_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),

    DownscaleUpscale(scale=0.25),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

sid_resize025_loader = DataLoader(
    SIDBinaryDataset(
        sid_validation,
        sid_resize025_transform
    ),
    batch_size=32,
    shuffle=False,
    num_workers=0
)

model_b_mix_sid_resize025 = evaluate_sid_model(
    mixed_model,
    sid_resize025_loader
)

In [ ]:
class FixedColorAdjustment:
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, image):
        image = TF.adjust_brightness(
            image,
            self.factor
        )

        image = TF.adjust_contrast(
            image,
            self.factor
        )

        image = TF.adjust_saturation(
            image,
            self.factor
        )

        return image

In [ ]:
def create_sid_color_loader(factor):
    color_transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),

        FixedColorAdjustment(factor),

        transforms.ToTensor(),

        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    return DataLoader(
        SIDBinaryDataset(
            sid_validation,
            color_transform
        ),
        batch_size=32,
        shuffle=False,
        num_workers=0
    )

In [ ]:
model_b_mix_sid_color_minus = evaluate_sid_model(
    mixed_model,
    create_sid_color_loader(0.8)
)

model_b_mix_sid_color_plus = evaluate_sid_model(
    mixed_model,
    create_sid_color_loader(1.2)
)

In [ ]:
print("Model B-Mix — SID severe endpoints")
print("----------------------------------")
print("Clean:        ", round(0.9057, 4))
print(
    "Blur 2.0:     ",
    round(model_b_mix_sid_blur2["roc_auc"], 4)
)
print(
    "Resize 0.25x: ",
    round(model_b_mix_sid_resize025["roc_auc"], 4)
)
print(
    "Colour -20%:  ",
    round(model_b_mix_sid_color_minus["roc_auc"], 4)
)
print(
    "Colour +20%:  ",
    round(model_b_mix_sid_color_plus["roc_auc"], 4)
)

Model B-Mix — SID severe endpoints
----------------------------------
Clean:         0.9057
Blur 2.0:      0.854
Resize 0.25x:  0.8497
Colour -20%:   0.8719
Colour +20%:   0.9005

In [ ]:
def create_sid_loader(transform):
    return DataLoader(
        SIDBinaryDataset(
            sid_validation,
            transform
        ),
        batch_size=32,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available()
    )

In [ ]:
sid_jpeg_results = {
    30: model_b_mix_sid_jpeg30
}

for quality in [90, 70, 50]:
    transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        JPEGCompression(quality),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    sid_jpeg_results[quality] = evaluate_sid_model(
        mixed_model,
        create_sid_loader(transform)
    )

    print(
        f"JPEG {quality} AUC:",
        round(sid_jpeg_results[quality]["roc_auc"], 4)
    )

JPEG 90 AUC: 0.8978
JPEG 70 AUC: 0.8921
JPEG 50 AUC: 0.8852

In [ ]:
sid_blur_results = {
    2.0: model_b_mix_sid_blur2
}

for sigma in [0.5, 1.0]:
    transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),

        transforms.GaussianBlur(
            kernel_size=5,
            sigma=sigma
        ),

        transforms.ToTensor(),

        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    sid_blur_results[sigma] = evaluate_sid_model(
        mixed_model,
        create_sid_loader(transform)
    )

    print(
        f"Blur {sigma} AUC:",
        round(sid_blur_results[sigma]["roc_auc"], 4)
    )

Blur 0.5 AUC: 0.8994
Blur 1.0 AUC: 0.8727

In [ ]:
sid_resize_results = {
    0.25: model_b_mix_sid_resize025
}

resize05_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),

    DownscaleUpscale(0.5),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

sid_resize_results[0.5] = evaluate_sid_model(
    mixed_model,
    create_sid_loader(resize05_transform)
)

print(
    "Resize 0.5x AUC:",
    round(sid_resize_results[0.5]["roc_auc"], 4)
)

Resize 0.5x AUC: 0.8619

In [ ]:
model_b_mix_sid_clean = evaluate_sid_model(
    mixed_model,
    sid_loader
)

print(
    "Confirmed clean SID AUC:",
    round(model_b_mix_sid_clean["roc_auc"], 4)
)

Confirmed clean SID AUC: 0.9057

In [ ]:
import pandas as pd
import numpy as np


sid_robustness_rows = [
    {
        "condition": "Clean",
        **model_b_mix_sid_clean
    },

    {
        "condition": "JPEG quality 90",
        **sid_jpeg_results[90]
    },
    {
        "condition": "JPEG quality 70",
        **sid_jpeg_results[70]
    },
    {
        "condition": "JPEG quality 50",
        **sid_jpeg_results[50]
    },
    {
        "condition": "JPEG quality 30",
        **sid_jpeg_results[30]
    },

    {
        "condition": "Blur sigma 0.5",
        **sid_blur_results[0.5]
    },
    {
        "condition": "Blur sigma 1.0",
        **sid_blur_results[1.0]
    },
    {
        "condition": "Blur sigma 2.0",
        **sid_blur_results[2.0]
    },

    {
        "condition": "Downscale 0.5x",
        **sid_resize_results[0.5]
    },
    {
        "condition": "Downscale 0.25x",
        **sid_resize_results[0.25]
    },

    {
        "condition": "Noise sigma 0.02",
        **model_b_mix_sid_noise002
    },
    {
        "condition": "Noise sigma 0.05",
        **model_b_mix_sid_noise005
    },
    {
        "condition": "Noise sigma 0.10",
        **model_b_mix_sid_noise010
    },

    {
        "condition": "Colour -20%",
        **model_b_mix_sid_color_minus
    },
    {
        "condition": "Colour +20%",
        **model_b_mix_sid_color_plus
    },

    {
        "condition": "Centre crop 80%",
        **model_b_mix_sid_crop080
    }
]

sid_robustness_table = pd.DataFrame(
    sid_robustness_rows
)

display(
    sid_robustness_table.round(4)
)

           condition  accuracy  roc_auc
0              Clean     0.820   0.9057
1    JPEG quality 90     0.850   0.8978
2    JPEG quality 70     0.800   0.8921
3    JPEG quality 50     0.805   0.8852
4    JPEG quality 30     0.795   0.8635
5     Blur sigma 0.5     0.810   0.8994
6     Blur sigma 1.0     0.790   0.8727
7     Blur sigma 2.0     0.765   0.8540
8     Downscale 0.5x     0.780   0.8619
9    Downscale 0.25x     0.760   0.8497
10  Noise sigma 0.02     0.810   0.8837
11  Noise sigma 0.05     0.765   0.8651
12  Noise sigma 0.10     0.750   0.8310
13       Colour -20%     0.805   0.8719
14       Colour +20%     0.795   0.9005
15   Centre crop 80%     0.815   0.8906

In [ ]:
sid_clean_auc = sid_robustness_table.loc[
    sid_robustness_table["condition"] == "Clean",
    "roc_auc"
].iloc[0]

sid_robust_auc = sid_robustness_table.loc[
    sid_robustness_table["condition"] != "Clean",
    "roc_auc"
].mean()

sid_final_score = (
    0.50 * sid_clean_auc
    + 0.50 * sid_robust_auc
)

worst_sid_condition = sid_robustness_table.loc[
    sid_robustness_table["condition"] != "Clean"
].sort_values("roc_auc").iloc[0]

print("Clean SID AUC:", round(sid_clean_auc, 4))
print("Robust SID AUC:", round(sid_robust_auc, 4))
print(
    "Provisional combined score:",
    round(sid_final_score, 4)
)
print(
    "Worst condition:",
    worst_sid_condition["condition"]
)
print(
    "Worst-condition AUC:",
    round(worst_sid_condition["roc_auc"], 4)
)

Clean SID AUC: 0.9057
Robust SID AUC: 0.8746
Provisional combined score: 0.8902
Worst condition: Noise sigma 0.10
Worst-condition AUC: 0.831

In [ ]:
sid_robustness_table.to_csv(
    "/content/model_b_mix_sid_robustness.csv",
    index=False
)

sid_robustness_table.to_json(
    "/content/model_b_mix_sid_robustness.json",
    orient="records",
    indent=2
)

from google.colab import files

files.download(
    "/content/model_b_mix_sid_robustness.csv"
)

files.download(
    "/content/model_b_mix_sid_robustness.json"
)

In [ ]:
from google.colab import files

uploaded = files.upload()

print("Uploaded files:", list(uploaded.keys()))

Saving Model B Mix.zip to Model B Mix.zip
Uploaded files: ['Model B Mix.zip']

In [ ]:
from pathlib import Path

model_zip_path = Path("/content/Model B Mix.zip")

print("ZIP exists:", model_zip_path.exists())
print(
    "ZIP size:",
    round(model_zip_path.stat().st_size / 1024**2, 2),
    "MB"
)

ZIP exists: True
ZIP size: 83.62 MB

In [ ]:
!mkdir -p "/content/model_b_mix"
!unzip -q "/content/Model B Mix.zip" -d "/content/model_b_mix"

print("Extraction completed.")

Extraction completed.

In [ ]:
checkpoint_files = list(
    Path("/content/model_b_mix").rglob("*.pth")
)

print("Checkpoints found:")

for path in checkpoint_files:
    print(path)

assert len(checkpoint_files) > 0, (
    "No .pth checkpoint was found inside the ZIP."
)

checkpoint_path = checkpoint_files[0]

print("Using:", checkpoint_path)

Checkpoints found:
/content/model_b_mix/Model B Mix/resnet50_model_b_mix_best.pth
Using: /content/model_b_mix/Model B Mix/resnet50_model_b_mix_best.pth

In [ ]:
import torch
import torch.nn as nn

from torchvision import models

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

checkpoint = torch.load(
    checkpoint_path,
    map_location=device,
    weights_only=False
)

mixed_model = models.resnet50(weights=None)

mixed_model.fc = nn.Linear(
    mixed_model.fc.in_features,
    2
)

mixed_model.load_state_dict(
    checkpoint["model_state_dict"]
)

mixed_model = mixed_model.to(device)
mixed_model.eval()

AI_CLASS_INDEX = checkpoint["ai_class_index"]
REAL_CLASS_INDEX = checkpoint[
    "class_to_idx"
]["REAL"]

print("Model B-Mix restored successfully")
print("Device:", device)
print("Experiment:", checkpoint.get("experiment"))
print("Best epoch:", checkpoint.get("best_epoch"))
print("Class mapping:", checkpoint["class_to_idx"])
print("AI class index:", AI_CLASS_INDEX)

Model B-Mix restored successfully
Device: cpu
Experiment: Model B-Mix
Best epoch: 3
Class mapping: {'FAKE': 0, 'REAL': 1}
AI class index: 0

In [ ]:
from google.colab import files

uploaded_test = files.upload()
test_zip_name = next(iter(uploaded_test.keys()))

print("Uploaded:", test_zip_name)

Saving Real Image.zip to Real Image.zip
Saving AI Image.zip to AI Image.zip
Uploaded: Real Image.zip

In [ ]:
from pathlib import Path

test_zip_path = Path("/content") / test_zip_name

!mkdir -p "/content/manual_test"
!unzip -q "$test_zip_path" -d "/content/manual_test"

for folder in Path("/content/manual_test").rglob("*"):
    if folder.is_dir():
        print(folder)

/content/manual_test/Real Image

In [ ]:
from pathlib import Path

image_extensions = {
    ".jpg", ".jpeg", ".png",
    ".webp", ".bmp"
}

test_root = Path("/content/manual_test")

for folder in [test_root] + [
    path
    for path in test_root.rglob("*")
    if path.is_dir()
]:
    image_count = sum(
        1
        for file in folder.iterdir()
        if file.is_file()
        and file.suffix.lower() in image_extensions
    )

    print(folder, "— images:", image_count)

/content/manual_test — images: 0
/content/manual_test/Real Image — images: 5

In [ ]:
from google.colab import files

uploaded_ai = files.upload()
ai_zip_name = next(iter(uploaded_ai.keys()))

ai_zip_path = Path("/content") / ai_zip_name

!unzip -q "$ai_zip_path" -d "/content/manual_test"

Saving AI Image.zip to AI Image (1).zip

In [ ]:
from pathlib import Path

image_extensions = {
    ".jpg", ".jpeg", ".png",
    ".webp", ".bmp"
}

test_root = Path("/content/manual_test")

for folder in [test_root] + [
    path
    for path in test_root.rglob("*")
    if path.is_dir()
]:
    image_count = sum(
        1
        for file in folder.iterdir()
        if file.is_file()
        and file.suffix.lower() in image_extensions
    )

    print(folder, "— images:", image_count)

/content/manual_test — images: 0
/content/manual_test/AI Image — images: 4
/content/manual_test/Real Image — images: 5

In [ ]:
from pathlib import Path
from PIL import Image

import torch
import numpy as np

from torch.utils.data import Dataset, DataLoader
from torchvision import transforms


test_root = Path("/content/manual_test")
real_folder = test_root / "Real Image"
ai_folder = test_root / "AI Image"

image_extensions = {
    ".jpg", ".jpeg", ".png",
    ".webp", ".bmp"
}

real_paths = [
    path
    for path in real_folder.rglob("*")
    if path.is_file()
    and path.suffix.lower() in image_extensions
]

ai_paths = [
    path
    for path in ai_folder.rglob("*")
    if path.is_file()
    and path.suffix.lower() in image_extensions
]

print("Real images:", len(real_paths))
print("AI images:", len(ai_paths))

assert len(real_paths) > 0, "No real images found."
assert len(ai_paths) > 0, "No AI images found."

Real images: 5
AI images: 4

In [ ]:
manual_test_transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


class ManualImageDataset(Dataset):
    def __init__(
        self,
        real_paths,
        ai_paths,
        transform
    ):
        # Evaluation convention:
        # 0 = real
        # 1 = AI
        self.samples = (
            [(path, 0) for path in real_paths]
            + [(path, 1) for path in ai_paths]
        )

        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, index):
        image_path, label = self.samples[index]

        image = Image.open(
            image_path
        ).convert("RGB")

        image = self.transform(image)

        return image, label, str(image_path)


manual_test_dataset = ManualImageDataset(
    real_paths,
    ai_paths,
    manual_test_transform
)

manual_test_loader = DataLoader(
    manual_test_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=0,
    pin_memory=torch.cuda.is_available()
)

print(
    "Total test images:",
    len(manual_test_dataset)
)

Total test images: 9

In [ ]:
from google.colab import files

uploaded_model = files.upload()

print(
    "Uploaded:",
    list(uploaded_model.keys())
)

KeyboardInterrupt:

In [ ]:
from pathlib import Path
import zipfile
import torch
import torch.nn as nn

from torchvision import models


uploaded_filename = next(
    iter(uploaded_model.keys())
)

model_zip_path = (
    Path("/content") / uploaded_filename
)

extraction_folder = Path(
    "/content/model_b_mix"
)

extraction_folder.mkdir(
    parents=True,
    exist_ok=True
)

with zipfile.ZipFile(
    model_zip_path,
    "r"
) as archive:
    archive.extractall(
        extraction_folder
    )

checkpoint_files = list(
    extraction_folder.rglob("*.pth")
)

assert len(checkpoint_files) > 0, (
    "No .pth checkpoint found inside ZIP."
)

checkpoint_path = checkpoint_files[0]

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

checkpoint = torch.load(
    checkpoint_path,
    map_location=device,
    weights_only=False
)

mixed_model = models.resnet50(
    weights=None
)

mixed_model.fc = nn.Linear(
    mixed_model.fc.in_features,
    2
)

mixed_model.load_state_dict(
    checkpoint["model_state_dict"]
)

mixed_model = mixed_model.to(device)
mixed_model.eval()

AI_CLASS_INDEX = checkpoint[
    "ai_class_index"
]

print("Model B-Mix restored successfully")
print("Checkpoint:", checkpoint_path)
print("Device:", device)
print("AI class index:", AI_CLASS_INDEX)

In [ ]:
from google.colab import files

uploaded_model = files.upload()

print(
    "Uploaded:",
    list(uploaded_model.keys())
)

Saving Model B Mix.zip to Model B Mix.zip
Uploaded: ['Model B Mix.zip']

In [ ]:
from pathlib import Path
import zipfile
import torch
import torch.nn as nn

from torchvision import models


uploaded_filename = next(
    iter(uploaded_model.keys())
)

model_zip_path = (
    Path("/content") / uploaded_filename
)

extraction_folder = Path(
    "/content/model_b_mix"
)

extraction_folder.mkdir(
    parents=True,
    exist_ok=True
)

with zipfile.ZipFile(
    model_zip_path,
    "r"
) as archive:
    archive.extractall(
        extraction_folder
    )

checkpoint_files = list(
    extraction_folder.rglob("*.pth")
)

assert len(checkpoint_files) > 0, (
    "No .pth checkpoint found inside ZIP."
)

checkpoint_path = checkpoint_files[0]

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

checkpoint = torch.load(
    checkpoint_path,
    map_location=device,
    weights_only=False
)

mixed_model = models.resnet50(
    weights=None
)

mixed_model.fc = nn.Linear(
    mixed_model.fc.in_features,
    2
)

mixed_model.load_state_dict(
    checkpoint["model_state_dict"]
)

mixed_model = mixed_model.to(device)
mixed_model.eval()

AI_CLASS_INDEX = checkpoint[
    "ai_class_index"
]

print("Model B-Mix restored successfully")
print("Checkpoint:", checkpoint_path)
print("Device:", device)
print("AI class index:", AI_CLASS_INDEX)

Model B-Mix restored successfully
Checkpoint: /content/model_b_mix/Model B Mix/resnet50_model_b_mix_best.pth
Device: cpu
AI class index: 0

In [ ]:
mixed_model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): Bottleneck(
      (conv1): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (2): Bottleneck(
      (conv1): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
  )
  (layer2): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): Bottleneck(
      (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (2): Bottleneck(
      (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (3): Bottleneck(
      (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
  )
  (layer3): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(512, 1024, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): Bottleneck(
      (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (2): Bottleneck(
      (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (3): Bottleneck(
      (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (4): Bottleneck(
      (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (5): Bottleneck(
      (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
  )
  (layer4): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): Bottleneck(
      (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
    (2): Bottleneck(
      (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
  (fc): Linear(in_features=2048, out_features=2, bias=True)
)

In [ ]:
from google.colab import files

uploaded_test = files.upload()
test_zip_name = next(iter(uploaded_test.keys()))

print("Uploaded:", test_zip_name)

Saving Real Image.zip to Real Image (1).zip
Saving AI Image.zip to AI Image (2).zip
Uploaded: Real Image (1).zip

In [ ]:
from pathlib import Path

test_zip_path = Path("/content") / test_zip_name

!mkdir -p "/content/manual_test"
!unzip -q "$test_zip_path" -d "/content/manual_test"

for folder in Path("/content/manual_test").rglob("*"):
    if folder.is_dir():
        print(folder)

replace /content/manual_test/Real Image/Chicken.webp? [y]es, [n]o, [A]ll, [N]one, [r]ename: /content/manual_test/AI Image
/content/manual_test/Real Image

In [ ]:
from pathlib import Path
from PIL import Image

import torch
import numpy as np

from torch.utils.data import Dataset, DataLoader
from torchvision import transforms


test_root = Path("/content/manual_test")
real_folder = test_root / "Real Image"
ai_folder = test_root / "AI Image"

image_extensions = {
    ".jpg", ".jpeg", ".png",
    ".webp", ".bmp"
}

real_paths = [
    path
    for path in real_folder.rglob("*")
    if path.is_file()
    and path.suffix.lower() in image_extensions
]

ai_paths = [
    path
    for path in ai_folder.rglob("*")
    if path.is_file()
    and path.suffix.lower() in image_extensions
]

print("Real images:", len(real_paths))
print("AI images:", len(ai_paths))

assert len(real_paths) > 0, "No real images found."
assert len(ai_paths) > 0, "No AI images found."

Real images: 5
AI images: 4

In [ ]:
from pathlib import Path
from PIL import Image
import torch
from torchvision import transforms
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix
import pandas as pd

# Confirm that the model is loaded
assert "mixed_model" in globals(), (
    "mixed_model is not loaded. Restore Model B-Mix before running this cell."
)

mixed_model = mixed_model.to(device)
mixed_model.eval()

# Same preprocessing used during validation
manual_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    ),
])

real_folder = Path("/content/manual_test/Real Image")
ai_folder = Path("/content/manual_test/AI Image")

valid_extensions = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}

test_files = []

for path in real_folder.iterdir():
    if path.suffix.lower() in valid_extensions:
        test_files.append((path, 0))  # 0 = Real

for path in ai_folder.iterdir():
    if path.suffix.lower() in valid_extensions:
        test_files.append((path, 1))  # 1 = AI

results = []

with torch.no_grad():
    for image_path, true_label in test_files:
        image = Image.open(image_path).convert("RGB")
        image_tensor = manual_transform(image).unsqueeze(0).to(device)

        outputs = mixed_model(image_tensor)
        probabilities = torch.softmax(outputs, dim=1)

        # Model output mapping: FAKE/AI = index 0
        ai_probability = probabilities[0, 0].item()
        real_probability = probabilities[0, 1].item()

        # Manual evaluation mapping: 0 = Real, 1 = AI
        predicted_label = 1 if ai_probability >= 0.5 else 0

        results.append({
            "filename": image_path.name,
            "actual": "AI" if true_label == 1 else "Real",
            "prediction": "AI" if predicted_label == 1 else "Real",
            "AI probability": ai_probability,
            "Real probability": real_probability,
            "correct": predicted_label == true_label,
            "true_label": true_label,
            "predicted_label": predicted_label,
        })

results_df = pd.DataFrame(results)

display(
    results_df[
        [
            "filename",
            "actual",
            "prediction",
            "AI probability",
            "Real probability",
            "correct",
        ]
    ].sort_values(["actual", "filename"])
)

true_labels = results_df["true_label"].tolist()
predicted_labels = results_df["predicted_label"].tolist()
ai_probabilities = results_df["AI probability"].tolist()

print("\nManual test accuracy:", round(
    accuracy_score(true_labels, predicted_labels), 4
))

print("Manual test ROC AUC:", round(
    roc_auc_score(true_labels, ai_probabilities), 4
))

print("\nConfusion matrix:")
print(confusion_matrix(true_labels, predicted_labels))
print("\nMatrix format: [[real predicted real, real predicted AI],")
print("                [AI predicted real, AI predicted AI]]")

,filename,actual,prediction,AI probability,Real probability,correct
8,"Codex Image Aug 30, 2026, 11_30_03 PM.png",AI,AI,0.612148,0.387852,True
7,"Codex Image Aug 30, 2026, 11_35_12 PM.png",AI,Real,0.053402,0.946598,False
5,"Codex Image Aug 30, 2026, 11_37_03 PM.png",AI,Real,0.445022,0.554978,False
6,images.jpg,AI,AI,0.576204,0.423796,True
0,Chicken.webp,Real,Real,0.215580,0.784420,True
2,images (1).jpg,Real,AI,0.667956,0.332044,False
3,images (2).jpg,Real,Real,0.174246,0.825754,True
4,images (3).jpg,Real,Real,0.476607,0.523393,True
1,images.jpg,Real,AI,0.604974,0.395026,False

Manual test accuracy: 0.5556
Manual test ROC AUC: 0.45

Confusion matrix:
[[3 2]
 [2 2]]

Matrix format: [[real predicted real, real predicted AI],
                [AI predicted real, AI predicted AI]]

In [ ]:
from pathlib import Path
from PIL import Image, ImageFilter, ImageEnhance
from io import BytesIO

import numpy as np
import pandas as pd
import torch

from torchvision import transforms
from sklearn.metrics import accuracy_score, roc_auc_score

assert "mixed_model" in globals(), "mixed_model is not loaded."
assert "device" in globals(), "device is not defined."

mixed_model = mixed_model.to(device)
mixed_model.eval()

# Model preprocessing
model_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    ),
])

RESAMPLE = Image.Resampling.LANCZOS

def resize_224(image):
    return image.resize((224, 224), RESAMPLE)


def jpeg_compress(image, quality=30):
    buffer = BytesIO()

    image.save(
        buffer,
        format="JPEG",
        quality=quality
    )

    buffer.seek(0)

    return Image.open(buffer).convert("RGB")


def downscale_upscale(image, scale=0.5):
    width, height = image.size

    small_width = max(1, int(width * scale))
    small_height = max(1, int(height * scale))

    small = image.resize(
        (small_width, small_height),
        RESAMPLE
    )

    return small.resize(
        (width, height),
        RESAMPLE
    )


def centre_crop(image, retained_fraction=0.8):
    width, height = image.size

    crop_width = int(width * retained_fraction)
    crop_height = int(height * retained_fraction)

    left = (width - crop_width) // 2
    top = (height - crop_height) // 2

    cropped = image.crop((
        left,
        top,
        left + crop_width,
        top + crop_height
    ))

    return cropped.resize(
        (width, height),
        RESAMPLE
    )


def create_transformed_views(original_image):
    # First standardize every image to 224×224.
    image = resize_224(original_image.convert("RGB"))

    return {
        "original": image,
        "jpeg_q30": jpeg_compress(image, quality=30),
        "blur_1": image.filter(
            ImageFilter.GaussianBlur(radius=1.0)
        ),
        "resize_05": downscale_upscale(image, scale=0.5),
        "crop_80": centre_crop(image, retained_fraction=0.8),
        "colour_minus20": ImageEnhance.Color(image).enhance(0.8),
        "colour_plus20": ImageEnhance.Color(image).enhance(1.2),
    }


def predict_ai_probability(image):
    tensor = model_transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        output = mixed_model(tensor)
        probability = torch.softmax(output, dim=1)

    # Model training mapping:
    # output 0 = FAKE/AI
    # output 1 = REAL
    return probability[0, 0].item()


# Locate manual test images
real_folder = Path("/content/manual_test/Real Image")
ai_folder = Path("/content/manual_test/AI Image")

valid_extensions = {
    ".jpg", ".jpeg", ".png", ".webp", ".bmp"
}

manual_files = []

for path in real_folder.iterdir():
    if path.suffix.lower() in valid_extensions:
        manual_files.append((path, 0))  # 0 = real

for path in ai_folder.iterdir():
    if path.suffix.lower() in valid_extensions:
        manual_files.append((path, 1))  # 1 = AI


# Run every image through every transformed view
consensus_results = []

for image_path, true_label in manual_files:
    image = Image.open(image_path).convert("RGB")
    views = create_transformed_views(image)

    view_probabilities = {
        view_name: predict_ai_probability(view_image)
        for view_name, view_image in views.items()
    }

    probability_values = list(view_probabilities.values())

    mean_probability = float(
        np.mean(probability_values)
    )

    median_probability = float(
        np.median(probability_values)
    )

    probability_std = float(
        np.std(probability_values)
    )

    median_prediction = int(
        median_probability >= 0.5
    )

    view_predictions = [
        int(probability >= 0.5)
        for probability in probability_values
    ]

    consensus_agreement = max(
        view_predictions.count(0),
        view_predictions.count(1)
    ) / len(view_predictions)

    row = {
        "filename": image_path.name,
        "actual": "AI" if true_label == 1 else "Real",
        "true_label": true_label,
        **view_probabilities,
        "mean_AI_probability": mean_probability,
        "median_AI_probability": median_probability,
        "probability_std": probability_std,
        "agreement": consensus_agreement,
        "consensus_prediction": (
            "AI" if median_prediction == 1 else "Real"
        ),
        "consensus_correct": median_prediction == true_label,
        "consensus_label": median_prediction,
    }

    consensus_results.append(row)


consensus_df = pd.DataFrame(consensus_results)

display_columns = [
    "filename",
    "actual",
    "original",
    "jpeg_q30",
    "blur_1",
    "resize_05",
    "crop_80",
    "colour_minus20",
    "colour_plus20",
    "median_AI_probability",
    "probability_std",
    "agreement",
    "consensus_prediction",
    "consensus_correct",
]

display(
    consensus_df[display_columns]
    .sort_values(["actual", "filename"])
    .round(4)
)


# Compare original prediction against consensus prediction
true_labels = consensus_df["true_label"].tolist()

original_probabilities = consensus_df["original"].tolist()
mean_probabilities = consensus_df["mean_AI_probability"].tolist()
median_probabilities = consensus_df["median_AI_probability"].tolist()

original_predictions = [
    int(probability >= 0.5)
    for probability in original_probabilities
]

mean_predictions = [
    int(probability >= 0.5)
    for probability in mean_probabilities
]

median_predictions = consensus_df[
    "consensus_label"
].tolist()

print("\n===== Original single-view model =====")
print(
    "Accuracy:",
    round(
        accuracy_score(
            true_labels,
            original_predictions
        ),
        4
    )
)
print(
    "ROC AUC:",
    round(
        roc_auc_score(
            true_labels,
            original_probabilities
        ),
        4
    )
)

print("\n===== Mean transformation consensus =====")
print(
    "Accuracy:",
    round(
        accuracy_score(
            true_labels,
            mean_predictions
        ),
        4
    )
)
print(
    "ROC AUC:",
    round(
        roc_auc_score(
            true_labels,
            mean_probabilities
        ),
        4
    )
)

print("\n===== Median transformation consensus =====")
print(
    "Accuracy:",
    round(
        accuracy_score(
            true_labels,
            median_predictions
        ),
        4
    )
)
print(
    "ROC AUC:",
    round(
        roc_auc_score(
            true_labels,
            median_probabilities
        ),
        4
    )
)

print("\nMean transformation agreement:")
print(
    round(
        consensus_df["agreement"].mean(),
        4
    )
)

,filename,actual,original,jpeg_q30,blur_1,resize_05,crop_80,colour_minus20,colour_plus20,median_AI_probability,probability_std,agreement,consensus_prediction,consensus_correct
8,"Codex Image Aug 30, 2026, 11_30_03 PM.png",AI,0.5738,0.4280,0.6719,0.4847,0.2823,0.5312,0.6016,0.5312,0.1185,0.5714,AI,True
7,"Codex Image Aug 30, 2026, 11_35_12 PM.png",AI,0.0539,0.0145,0.0866,0.1274,0.0575,0.0383,0.0699,0.0575,0.0334,1.0000,Real,False
5,"Codex Image Aug 30, 2026, 11_37_03 PM.png",AI,0.3695,0.0893,0.4110,0.3197,0.2057,0.3481,0.4112,0.3481,0.1103,1.0000,Real,False
6,images.jpg,AI,0.5606,0.5246,0.5737,0.6415,0.4939,0.5465,0.5682,0.5606,0.0426,0.8571,AI,True
0,Chicken.webp,Real,0.2493,0.1745,0.1018,0.0911,0.1656,0.2422,0.2548,0.1745,0.0638,1.0000,Real,True
2,images (1).jpg,Real,0.6820,0.3596,0.7525,0.8179,0.8345,0.6615,0.6892,0.6892,0.1469,0.8571,AI,False
3,images (2).jpg,Real,0.1958,0.1105,0.2304,0.2728,0.3263,0.2093,0.1945,0.2093,0.0627,1.0000,Real,True
4,images (3).jpg,Real,0.5172,0.4947,0.5224,0.5768,0.6102,0.5097,0.5048,0.5172,0.0397,0.8571,AI,False
1,images.jpg,Real,0.6111,0.5424,0.7286,0.6782,0.5666,0.5996,0.6036,0.6036,0.0595,1.0000,AI,False

===== Original single-view model =====
Accuracy: 0.4444
ROC AUC: 0.4

===== Mean transformation consensus =====
Accuracy: 0.4444
ROC AUC: 0.35

===== Median transformation consensus =====
Accuracy: 0.4444
ROC AUC: 0.4

Mean transformation agreement:
0.9048